dependencies {
    api project(":grace-api")
    api project(":grace-plugin-api")
    api project(":grace-web-common")
    api project(":grace-web-databinding")
    api project(":grace-web-gsp")
    api project(":grace-web-mvc")
    api project(":grace-web-sitemesh")
    api project(":grace-web-taglib")
    api project(":grace-web-url-mappings")

    compileOnlyApi libs.jakarta.servlet
    compileOnly libs.grace.datastore.gorm.support

    testImplementation libs.jakarta.servlet
    testImplementation project(":grace-test")
}
