dependencies {
    api project(":grace-api")
    api project(":grace-codecs")
    api project(":grace-core")
    api project(":grace-encoder")
    api project(":grace-plugin-api")

    api libs.spring.boot.autoconfigure
    annotationProcessor libs.spring.boot.autoconfigureProcessor
    annotationProcessor libs.spring.boot.configurationProcessor

    testImplementation libs.jakarta.servlet
    testImplementation project(":grace-test")
    testImplementation project(":grace-web")
}
