dependencies {
    api project(":grace-core")
    api project(":grace-util")
    api libs.grace.datastore.gorm.validation

    testImplementation project(":grace-plugin-domain-class")
    testImplementation project(":grace-web")
    testImplementation libs.jakarta.servlet
    testImplementation libs.spring.test
}
