dependencies {
    api project(":grace-boot")
    api project(":grace-bootstrap")
    api project(":grace-core")
    // compileOnly "org.spockframework:spock-core", {
    //     exclude group: "junit", module: "junit-dep"
    //     exclude group: 'org.codehaus.groovy', module: 'groovy-all'
    //     exclude group: 'org.hamcrest', module: 'hamcrest-core'
    // }

    api libs.grace.datastore.core
    api libs.grace.datastore.gorm
    api libs.grace.datastore.gorm.mongodb
    api libs.grace.datastore.gorm.mongodb.ext
    api libs.grace.datastore.gorm.support
    api libs.grace.datastore.web

    api libs.spring.boot.autoconfigure
    annotationProcessor libs.spring.boot.autoconfigureProcessor
    annotationProcessor libs.spring.boot.configurationProcessor
    testImplementation libs.spock.core
}
