dependencies {
    compileOnly project(":grace-boot")
    api project(":grace-bootstrap")
    api project(":grace-core")
    compileOnly project(":grace-plugin-api")

    api libs.grace.datastore.core
    api libs.grace.datastore.gorm
    api libs.grace.datastore.gorm.mongodb
    api libs.grace.datastore.gorm.support
    api libs.grace.datastore.web

    api libs.spring.boot.autoconfigure
    annotationProcessor libs.spring.boot.autoconfigureProcessor
    annotationProcessor libs.spring.boot.configurationProcessor
    testImplementation libs.spock.core
}
