group = "org.graceframework.plugins"

dependencies {
    api project(':views-json')
    compileOnly "org.graceframework:grace-plugin-rest"
    compileOnly "jakarta.servlet:jakarta.servlet-api"
    compileOnly "org.graceframework:grace-datastore-gorm-mongodb"
}

def compileViews = tasks.register("compileViews", JavaExec) {
    inputs.files 'src/templates'
    outputs.dir 'build/classes/groovy/main'
    mainClass.set("grails.plugin.json.view.JsonViewCompiler")
    classpath configurations.compileClasspath + configurations.runtimeClasspath
    args("src/templates", "build/classes/groovy/main", "11", ' ', ' ', "none", "UTF-8")
}

sourceSets {
    main {
        resources {
            srcDirs = ['src/templates']
        }
    }
}

classes.dependsOn(compileViews)
