dependencies {
    compileOnly project(":grace-plugin-api")
    implementation project(":grace-plugin-controllers")
    api libs.grace.async.core
    api(libs.grace.datastore.gorm.support) {
        transitive = false
    }
    compileOnly libs.jakarta.servlet

    api libs.spring.boot.autoconfigure
    annotationProcessor libs.spring.boot.autoconfigureProcessor
    annotationProcessor libs.spring.boot.configurationProcessor

    testImplementation project(":grace-test")
    testImplementation libs.jakarta.servlet
    testImplementation libs.spring.test
}
