api=../api
tags=../ref/Tags
guide=../../guide
sourcedir=.
sourceRepo=https://github.com/graceframework/grace-database-migration/edit/6.3.x/src/docs
safe=UNSAFE
title=Grace Database Migration Plugin
subtitle=Helps you manage database changes while developing Grace applications
authors=Michael Yan
copyright=Copyright &copy; 2022-2025 Michael Yan and the original authors. The content is licensed under a Creative Commons Attribution 4.0 International (CC BY SA 4.0) license.
