group = "org.graceframework.plugins"

dependencies {
    api "jakarta.annotation:jakarta.annotation-api:$jakartaAnnotationVersion"
    api "org.graceframework:grace-core:$graceVersion"
    compileOnly "jakarta.servlet:jakarta.servlet-api:$servletApiVersion"
    compileOnly "org.graceframework:grace-boot:$graceVersion"
    api project(":views-core")

    api "org.springframework.boot:spring-boot-autoconfigure:$springBootVersion"
    annotationProcessor "org.springframework.boot:spring-boot-autoconfigure-processor:$springBootVersion"
    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor:$springBootVersion"
    testImplementation "org.graceframework:grace-test-support:$graceVersion"
}
