name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
categories:
  - title: ⭐️ Features
    labels:
      - "type: feature"
      - "type: epic"
  - title: 🐞 Bug Fixes
    labels:
      - "bug"
  - title: 🛠 Improvements
    labels:
      - "type: enhancement"
  - title: 🛠 Dependency Upgrades
    labels:
      - "type: dependency-upgrade"
  - title: ⚙️ Build/CI
    labels:
      - "type: ci"
      - "type: task"
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'type: major'
  minor:
    labels:
      - 'type: minor'
  patch:
    labels:
      - 'type: patch'
  default: patch
template: |
  ## What's Changed

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
