projectVersion=6.3.0-SNAPSHOT
graceVersion=2023.3.0-RC1
gormVersion=2023.3.0-RC1
groovyVersion=4.0.26
jansiVersion=1.18
javaParserCoreVersion=3.26.4
joddWotVersion=3.3.8
objenesisVersion=3.4
scaffoldingVersion=6.3.0-RC1
asciidoc=true
githubSlug=graceframework/grace-fields
githubBranch=master
title=Grace Fields Plugin
projectDesc=Customizable form-field rendering based on overrideable GSP template
guide=../../guide
projectUrl=https://github.com/graceframework/grace-fields
developers=Michael Yan