projectVersion=6.1.0-SNAPSHOT
projectUrl=https://views.graceframework.org
assetPipelineVersion=6.1.0-M3
caffeineVersion=3.1.8
functionalTestViewsGradleVersion=6.0.0
githubSlug=graceframework/grace-views
gormVersion=2023.1.0-RC1
gradleWrapperVersion=7.6.4
graceVersion=2023.1.0-M3
groovyVersion=4.0.23
bytebuddyVersion=1.14.16
jakartaAnnotationVersion=2.1.1
jansiVersion=2.4.0
javaParserCoreVersion=3.26.2
javassistVersion=3.30.0-GA
junitJupiterVersion=5.9.3
junitJupiterPlatformVersion=1.9.3
micronautVersion=3.5.7
mongodbDriverVersion=4.5.0
mongodbVersion=7.3.0
servletApiVersion=6.0.0
spockVersion=2.3-groovy-4.0
springDependencyManagementPluginVersion=1.1.6

org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1536M -XX:MaxMetaspaceSize=512M
