projectVersion=6.3.0-SNAPSHOT
projectUrl=https://views.graceframework.org
assetPipelineVersion=6.3.0
functionalTestViewsGradleVersion=6.3.0-M1
githubSlug=graceframework/grace-views
graceVersion=2023.3.0-RC2
gormVersion=2023.3.0
groovyVersion=4.0.26
javaParserCoreVersion=3.26.4

org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1536M -XX:MaxMetaspaceSize=512M
