rootProject.name = "Grace.Framework"

include (
        'docs',
        'grace-api',
        'grace-boot',
        'grace-boot-async',
        'grace-boot-cache',
        'grace-boot-events',
        'grace-boot-hibernate',
        'grace-boot-logging',
        'grace-boot-mongodb',
        'grace-boot-persistence',
        'grace-boot-plugin',
        'grace-boot-rest',
        'grace-boot-validation',
        'grace-boot-web',
        'grace-bootstrap',
        'grace-cache-core',
        'grace-cli',
        'grace-codecs',
        'grace-console',
        'grace-core',
        'grace-databinding',
        'grace-docs',
        'grace-encoder',
        'grace-gsp',
        'grace-logging',
        'grace-scaffolding-core',
        'grace-shell',
        // 'grace-sitemesh',
        'grace-spring',
        // 'grace-spring-boot',
        'grace-taglib',
        'grace-test',
        'grace-test-support',
        'grace-util',
        'grace-views-core',
        'grace-views-json',
        'grace-views-markup',
        'grace-web',
        'grace-web-gsp',
        'grace-web-mvc',
        'grace-web-rest',
        'grace-web-taglib',
        'grace-web-url-mappings',

        // POM / BOMs
        'grace-dependencies',
        'grace-bom',

        // Plugins
        'grace-plugin-api',
        'grace-plugin-async',
        'grace-plugin-cache',
        'grace-plugin-codecs',
        'grace-plugin-controllers',
        'grace-plugin-converters',
        'grace-plugin-core',
        'grace-plugin-database-migration',
        'grace-plugin-databinding',
        'grace-plugin-datasource',
        'grace-plugin-domain-class',
        'grace-plugin-dynamic-modules',
        'grace-plugin-events',
        'grace-plugin-fields',
        'grace-plugin-geb',
        'grace-plugin-gsp',
        'grace-plugin-interceptors',
        'grace-plugin-i18n',
        'grace-plugin-management',
        'grace-plugin-mimetypes',
        'grace-plugin-rest',
        'grace-plugin-scaffolding',
        'grace-plugin-services',
        'grace-plugin-taglibs',
        'grace-plugin-url-mappings',
        'grace-plugin-validation',

        // Test Suite
        'grace-test-suite-base',
        'grace-test-suite-persistence',
        'grace-test-suite-uber',
        'grace-test-suite-web',

        // Gradle Plugin
        'grace-gradle-model',
        'grace-gradle-plugin'
)