dependencies {
    api project(":grace-api")
    api project(":grace-bootstrap")
    api project(":grace-core")
    compileOnly project(":grace-cli")
    compileOnly project(":grace-plugin-api")
    api project(":grace-plugin-controllers")
    api project(":grace-util")
    api project(":grace-web-url-mappings")

    compileOnly libs.jakarta.servlet
    compileOnly libs.jansi
    compileOnly libs.jline

    compileOnly libs.spring.boot.actuator
    api libs.spring.boot.autoconfigure
    annotationProcessor libs.spring.boot.autoconfigureProcessor
    annotationProcessor libs.spring.boot.configurationProcessor

    testImplementation libs.jakarta.servlet
    testImplementation libs.spring.test
    testImplementation project(":grace-test")
}
