dependencies {
    compileOnly libs.jakarta.annotation.api
    compileOnlyApi libs.jakarta.servlet
    api project(":grace-api")
    api project(":grace-taglib")
    api project(":grace-web")

    testImplementation libs.jakarta.servlet
    testImplementation libs.spring.test
    testRuntimeOnly project(":grace-spring")
}
