dependencies {
    compileOnlyApi libs.jakarta.servlet
    compileOnlyApi libs.sitemesh, {
        exclude group: 'jakarta.servlet', module: 'jakarta.servlet-api'
    }
    api project(':grace-gsp')
    api project(':grace-taglib')
    api project(':grace-web-gsp')
    api project(':grace-web-taglib')
}
