dependencies {
    api project(":grace-api")
    api project(":grace-bootstrap")
    api project(":grace-core")
    api project(":grace-plugin-api")
    api project(":grace-plugin-core")
    api project(":grace-spring")

    api libs.jakarta.annotation.api
    compileOnly libs.jakarta.servlet
    api libs.spring.beans
    api libs.spring.boot
    api libs.spring.boot.autoconfigure
    annotationProcessor libs.spring.boot.autoconfigureProcessor
    annotationProcessor libs.spring.boot.configurationProcessor
    api libs.spring.context
    api libs.spring.core
    api libs.spring.web
    api libs.spring.webmvc

    compileOnly libs.jsr305
    compileOnly libs.spring.boot.devtools

    testImplementation project(":grace-logging")
    testImplementation project(":grace-plugin-controllers")
    testImplementation project(":grace-test")

    testImplementation libs.assertj.core
    testImplementation libs.mockito.core
    testImplementation libs.mockito.junit
    testImplementation libs.grace.datastore.gorm.support
    testImplementation libs.spring.boot.test
    testImplementation libs.tomcat.embed.core
    testRuntimeOnly project(":grace-plugin-i18n")
    testRuntimeOnly project(":grace-plugin-url-mappings")
}
