dependencies {
    api project(":grace-core")
    api project(":grace-cli")
    api project(":grace-plugin-controllers")
    api project(":grace-plugin-rest")
    api project(":grace-scaffolding-core")
    api project(":grace-web-gsp")
    compileOnly libs.jakarta.servlet
    api libs.spring.boot.autoconfigure
    annotationProcessor libs.spring.boot.autoconfigureProcessor
    annotationProcessor libs.spring.boot.configurationProcessor
}

tasks.register("syncScripts", Sync) {
    from("src/main/scripts")
    into("build/resources/main/META-INF/commands")
}

tasks.register("syncTemplates", Sync) {
    from("src/main/templates")
    into("build/resources/main/META-INF/templates")
}

processResources {
    dependsOn = ["syncScripts", "syncTemplates"]
}
