group = "org.graceframework.plugins"

ext {
    userOrg = 'graceframework'
    repo = 'grace-views'
    isGrailsPlugin = false
    projectDesc = "Grace JSON Views Templates"
}

repositories {
    mavenCentral()
    maven {
        url = "https://repo.grails.org/grails/core"
    }
}

dependencies {
    api project(':views-json')
    compileOnly "org.graceframework:grace-plugin-rest:$graceVersion"
    compileOnly "jakarta.servlet:jakarta.servlet-api:$servletApiVersion"
    compileOnly "org.grails:grails-datastore-gorm-mongodb:$mongodbVersion", {
        exclude group: 'org.codehaus.groovy', module: 'groovy'
        exclude group: 'org.codehaus.groovy', module: 'groovy-templates'
    }
}

def compileViews = tasks.register("compileViews", JavaExec) {
    inputs.files 'src/templates'
    outputs.dir 'build/classes/groovy/main'
    mainClass.set("grails.plugin.json.view.JsonViewCompiler")
    classpath configurations.compileClasspath + configurations.runtimeClasspath
    args("src/templates", "build/classes/groovy/main", "11", ' ', ' ', "none", "UTF-8")
}

sourceSets {
    main {
        resources {
            srcDirs = ['src/templates']
        }
    }
}

classes.dependsOn(compileViews)
