Please follow these instructions in order to complete your installation.

=== Prerequisites

Grace CLI requires Java JDK v17.0 or above in order to run. Groovy v4.0.x is packaged as part of this distribution, and therefore does not need to be installed (any
existing Groovy installation is ignored).

Grace CLI will use whatever JDK it finds on your path, to check that you have an appropriate version you should run:

[source,console]
----
$ java -version
----

Alternatively, you can set the JAVA_HOME environment variable to point a suitable JDK.

=== Environment Variables

No specific environment variables are required to run the CLI, however, you may want to set GRACE_HOME to point to a specific installation. You should also add GRACE_HOME/bin to your PATH environment variable.

=== Checking Your Installation

To test if you have successfully installed the CLI you can run the following command:

[source,console]
----
$ grace -v
----

If you see the output like below, congratulations, you have installed it successfully.

[source,console,subs="attributes"]
----
------------------------------------------------------------
Grace {version}
------------------------------------------------------------

Build time:   2026-04-01 13:30:19 UTC
Revision:     b5a5f6d1d0932a269c9fbcbbffa2ead6f6347318

Spring Boot:  3.4.13
Gradle:       8.14.4
Groovy:       4.0.30
JVM:          17.0.15 (BellSoft 17.0.15+10-LTS)
OS:           Mac OS X 12.7.6 aarch64
----
