Please follow these instructions in order to complete your installation.

=== Prerequisites

Grace CLI requires Java JDK v17.0 or above in order to run. Groovy v4.0.x is packaged as part of this distribution, and therefore does not need to be installed (any
existing Groovy installation is ignored).

Grace CLI will use whatever JDK it finds on your path, to check that you have an appropriate version you should run:

[source,console]
----
$ java -version
----

Alternatively, you can set the JAVA_HOME environment variable to point a suitable JDK.

=== Environment Variables

No specific environment variables are required to run the CLI, however, you may want to set GRACE_HOME to point to a specific installation. You should also add GRACE_HOME/bin to your PATH environment variable.

=== Using SDKMAN

SDKMAN! (The Software Development Kit Manager) can be used for managing multiple versions of various binary SDKs, including Groovy, Gradle and the Grace.
Get SDKMAN! from sdkman.io and install Grace by using the following commands:

```bash
$ sdk install grace
```

=== Checking Your Installation

To test if you have successfully installed the CLI you can run the following command:

[source,console]
----
$ grace -v
----

If you see the output like below, congratulations, you have installed it successfully.

[source,console,subs="attributes"]
----
------------------------------------------------------------
Grace {version}
------------------------------------------------------------

Build time:   2026-06-13 19:35:23 UTC
Revision:     5044df133be187a7adb7c193b062a537606e6a6c

Spring Boot:  3.5.15
Gradle:       8.14.5
Groovy:       4.0.32
JVM:          17.0.19 (Azul Systems, Inc. 17.0.19+10-LTS)
OS:           Mac OS X 12.7.6 aarch64
----
