
https://github.com/graceframework/grace-framework[Grace] is a fork of https://github.com/apache/grails-core/tree/5.1.x[Grails 5.1.x] that started development in early 2022, it's a powerful and open-source One-Person web framework used to build enterprise-grade https://spring.io/projects/spring-boot/[Spring Boot] applications with the powerful https://groovy-lang.org/[Groovy] programming language. The core framework is very extensible and there are numerous https://github.com/grace-plugins/[Plugins] available that provide easy integration of add-on features.

=== Why Grace?

Grace inherits the excellent concepts and designs of Grails, and based on this, has undergone significant restructuring to ensure that each module is independent and decoupled, such as Grace API, Grace Boot, Grace CLI, Grace Plugin API, Grace Plugin Core, Grace Spring Boot, Grace Util. Meanwhile, in order to better focus on maintenance and upgrades, Grace also merged the previously spun-off modules, Converters plugin, GSP, Grace Test Support. Grace Boot as an https://graceframework.org/grace-framework/2023.3.x/api/grails/boot/config/GrailsAutoConfiguration.html[Auto-configuration], it will load all other modules and plugins. Grace follows good modular design, and these modules can be used independently in Spring Boot applications.

Spring is the foundation for Grace, which is built on top of Spring Boot. To better support Spring Boot and integrate with other Spring ecosystems, Grace has rewritten `Plugin.doWithSpring()` using Spring Boot's https://docs.spring.io/spring-boot/3.3/reference/using/auto-configuration.html[Auto-configuration], which also reduces redundant configurations and provides significant performance improvements. Grace has also provided https://docs.spring.io/spring-boot/3.3/specification/configuration-metadata/index.html[Configuration Metadata] files include in Grace plugins' jars, the files are designed to let IDE developers offer contextual help and “code completion” as users are working with application.properties or application.yaml files. So, a Grace plugin is an extended Spring Boot Starter.

It is worth mentioning that Grace supports all current versions of Spring Boot, including https://github.com/graceframework/grace-framework/releases/tag/v2022.2.9[2.7], https://github.com/graceframework/grace-framework/releases/tag/v2023.0.3[3.0], https://github.com/graceframework/grace-framework/releases/tag/v2023.1.0[3.1], https://github.com/graceframework/grace-framework/releases/tag/v2023.2.0[3.2], https://github.com/graceframework/grace-framework/releases/tag/v2023.3.0[3.3], https://github.com/graceframework/grace-framework/releases/tag/v2024.0.0[3.4], and  https://github.com/graceframework/grace-framework/releases/tag/v2024.1.0-RC1[3.5]. This makes the upgrade path easier and more manageable.

Grace has been actively developing, bringing numerous improvements and new features, including Plugins, GSP, Console, Shell, and https://github.com/grace-profiles[Profiles]. Of course, it has also fixed a large number of legacy defects left in Grails 5, this makes developers happy.

You can learn more on the page https://github.com/graceframework/grace-framework/wiki/What's-New-in-Grace-Framework[What's New in Grace Framework].

=== Grace vs Spring Boot

Grace and Spring Boot frameworks are excellent for building web applications, but their use depends on what you want. Generally, Grace framework may be advantageous in full-stack and monolithic applications, but Spring Boot is preferred for developing complex and microservice applications.

Grace is not a replacement for Spring Boot, it is built on top of Spring Boot. It provides its' own https://docs.spring.io/spring-boot/3.3/reference/features/developing-auto-configuration.html#features.developing-auto-configuration.custom-starter[Spring Boot Starters] - Grace Boot as an AutoConfiguration, it will load all other modules and plugins. Grace follows good modular design, and these modules can be used independently in Spring Boot applications. So, a Grace application is really a Spring Boot application.

Grace has better developer productivity than Spring Boot. Because it follows the convention over the configuration principle, it minimizes code requirements. This enhances productivity and fosters faster app development. The framework creates faster and more functional prototypes than Spring Boot due to its simple code generation like scaffolding and CoC.

Grace has better support Groovy than Spring Boot. Grace fully embraces Groovy to enable many features that would not be possible using Java alone, including flexible and powerful Plug-in architecture and a rich https://github.com/grace-plugins[Plugin ecosystem] and many built-in https://github.com/grace-plugins/grace-dynamic-modules[Dynamic Module types], many https://docs.groovy-lang.org/latest/html/documentation/#_domain_specific_languages[DSLs], https://docs.groovy-lang.org/latest/html/documentation/#_available_ast_transformations[AST Transformations], https://docs.groovy-lang.org/latest/html/documentation/#_traits[Trait]-based solutions, and much more.

Grace provides a powerful CLI that allows you to quickly create new projects of many different types using https://github.com/grace-profiles[Application Profiles] and https://github.com/grace-templates[Templates] and get started easily. These are all extensible and easy to customize, you can create your own Profiles, Templates, and Commands to meet any of your needs. The learning curve for Grace is moderate and more straightforward than Spring Boot due to its emphasis on convention and simplicity.

You can learn more on the page https://github.com/graceframework/grace-framework/wiki/Grace-vs-Spring-Boot[Grace vs Spring Boot].
