group = "org.graceframework.plugins"

dependencies {
    api project(":views-core")
    api "jakarta.annotation:jakarta.annotation-api"
    api "org.graceframework:grace-core", {
        exclude group: 'org.graceframework', module: 'grace-datastore-core'
    }

    api "org.springframework.boot:spring-boot-autoconfigure"
    annotationProcessor "org.springframework.boot:spring-boot-autoconfigure-processor"
    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"

    testImplementation "org.graceframework:grace-test-support"
    testImplementation project(":views-json-testing-support")
    testImplementation "net.bytebuddy:byte-buddy"
}

jar {
    exclude "*.gson"
}
