springApi=https://docs.spring.io/spring-framework/docs/6.1.19/javadoc-api
api=../api
tags=../ref/Tags
guide=../../guide
sourcedir=.
sourceRepo=https://github.com/graceframework/grace-cache/edit/6.3.x/src/main/docs
safe=UNSAFE
githubSlug=graceframework/grace-cache
githubBranch=6.3.x
title=Grace Cache
subtitle=Provides AST transformations for caching method calls
authors=Michael Yan
copyright=Copyright &copy; 2022-2025 Michael Yan and the original authors. The content is licensed under a Creative Commons Attribution 4.0 International (CC BY SA 4.0) license.
