// Gradle assemble tasks
import org.grails.gradle.GraceCreateStartScripts

tasks.register('createGraceStartScripts', GraceCreateStartScripts) {
    defaultJvmOpts = ["-XX:+TieredCompilation", "-XX:TieredStopAtLevel=1", "-XX:CICompilerCount=3"]
    outputDir = file('bin')
    classpath = rootProject.childProjects['grace-shell'].configurations.runtimeClasspath
    unixStartScriptTemplate = rootProject.childProjects['grace-shell'].resources.text.fromFile('src/main/resources/unixStartScript.txt')
    windowsStartScriptTemplate = rootProject.childProjects['grace-shell'].resources.text.fromFile('src/main/resources/windowsStartScript.txt')
    projectArtifacts = rootProject.childProjects['grace-shell'].tasks['jar'].outputs.files.collect { "dist/${it.name}" }

    doLast {
        ant.replace(file: file('bin/grace'), token: 'APP_HOME', value: 'GRACE_HOME')
        ant.replace(file: file('bin/grace.bat'), token: 'APP_HOME', value: 'GRACE_HOME')
        ant.replace(file: file('bin/grace'), token: 'media/gradle.icns', value: 'media/icons/grace.icns')

        def resolvedArtifacts = rootProject.childProjects['grace-shell']
                .configurations.runtimeClasspath.resolvedConfiguration.resolvedArtifacts
        for (artifact in resolvedArtifacts) {
            def dependency = artifact.moduleVersion.id
            if (dependency.group == 'org.graceframework') {
                ant.copy(file: artifact.file, todir: "${homeLibDir}/org.graceframework")
            } else {
                ant.copy(file: artifact.file, todir: "${homeLibDir}/${dependency.group}/${dependency.name}/jars")
            }
        }
    }
}

tasks.register('install') {
    dependsOn = [createGraceStartScripts]
    subprojects { Project project ->
        if (project.name != 'docs' && !project.name.startsWith('grace-test-suite')) {
            dependsOn("$project.name:publishToMavenLocal")
        }
    }
}

tasks.register('publishToDist') {
    subprojects { Project project ->
        if (project.name != 'docs' && !project.name.startsWith('grace-test-suite') && !project.name.startsWith('grace-dependencies') && !project.name.startsWith('grace-bom')) {
            project.tasks.named("generateMetadataFileForIvyPublication").configure {
                enabled = false
            }
            dependsOn("$project.name:publishAllPublicationsToGraceDistRepository")
        }
    }
}

tasks.register('binZip', Zip) {
    dependsOn = [publishToDist, createGraceStartScripts]
    destinationDirectory = rootProject.layout.buildDirectory.dir('distributions')
    archiveBaseName = 'grace'
    archiveAppendix = grailsVersion
    archiveClassifier = 'bin'

    into("grace-$grailsVersion") {
        from(projectDir) {
            include 'bin/grace', 'bin/grace.bat', 'LICENSE.txt', 'INSTALL.txt'
        }
        from("lib") {
            into "lib"
            exclude "org.graceframework/**"
        }
        from("lib/org.graceframework") {
            into "dist"
            include '**/*.jar'
        }
        from(homeDistDir) {
            into "dist"
            include "grace-shell-*.jar"
            exclude "*.zip*"
            exclude "*.tar*"
            exclude '*-javadoc.jar*', '*-sources.jar*', 'ivy-*', '*.jar.sha*'
        }
    }
}

tasks.register('sourcesZip', Zip) {
    dependsOn = [publishToDist]
    destinationDirectory = rootProject.layout.buildDirectory.dir('distributions')
    archiveBaseName = 'grace'
    archiveAppendix = grailsVersion
    archiveClassifier = 'sources'

    into("grace-$grailsVersion") {
        from(projectDir) {
            include 'LICENSE.txt'
        }
        from(homeDistDir) {
            into "src"
            include '*-sources.jar', '*-sources.jar.sha*'
        }
    }
}

tasks.register('docsZip', Zip) {
    dependsOn = ['docs:docs']
    destinationDirectory = rootProject.layout.buildDirectory.dir('distributions')
    archiveBaseName = 'grace'
    archiveAppendix = grailsVersion
    archiveClassifier = 'docs'

    into("grace-$grailsVersion") {
        from(projectDir) {
            include 'LICENSE.txt'
        }
        from("$projectDir/docs/build/docs/manual") {
            into "docs"
        }
    }
}

tasks.register('zipDist') {
    dependsOn = [binZip, sourcesZip, docsZip]
}

tasks.register('assemble') {
    dependsOn = [install, zipDist]
}
