// Gradle assemble tasks

def libsConfigurations = []
subprojects { subproject ->
    if (subproject.name == 'grace-dependencies') return
    if (subproject.name == 'grace-bom') return
    if (subproject.name == 'grace-shell') {
        configurations {
            libsConfigurations << libs {
                extendsFrom runtimeClasspath
                attributes {
                    attribute(Usage.USAGE_ATTRIBUTE, subproject.objects.named(Usage, Usage.JAVA_RUNTIME))
                    attribute(Category.CATEGORY_ATTRIBUTE, subproject.objects.named(Category, Category.LIBRARY))
                }
            }
        }
    }
}

task configurePopulateDependencies(dependsOn: 'publishToDist') {
    doLast {
        def projectNames = rootProject.subprojects*.name

        def seen = []
        libsConfigurations.each { configuration ->
            for (artifact in configuration.resolvedConfiguration.resolvedArtifacts) {
                if (artifact in seen) continue
                seen << artifact
                def dependency = artifact.moduleVersion.id
                if (!projectNames.contains(dependency.name)) {
                    if (dependency.group == 'org.graceframework') {
                        populateDependencies.into('org.graceframework') {
                            from artifact.file // this will trigger the actual download if necessary
                        }
                    } else {
                        populateDependencies.into("$dependency.group/$dependency.name/jars") {
                            from artifact.file // this will trigger the actual download if necessary
                        }
                    }
                } else {
                    populateDependencies.into('org.graceframework') {
                        from(homeDistDir) {
                            include artifact.file.name
                        }
                    }
                }
            }
        }
    }
}

task populateDependencies(type: Sync, dependsOn: configurePopulateDependencies) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    into homeLibDir
    includeEmptyDirs = false
}

task grailsCreateStartScripts(type: GrailsCreateStartScripts, dependsOn: populateDependencies) {
    description = "Creates OS specific scripts to run grace-shell as a JVM application."
    mainClass = 'org.grails.cli.GrailsCli'
    applicationName = 'grace'
    defaultJvmOpts = ["-XX:+TieredCompilation", "-XX:TieredStopAtLevel=1", "-XX:CICompilerCount=3"]
    outputDir = file('bin')
    classpath = rootProject.childProjects['grace-shell'].configurations.runtimeClasspath
    projectArtifacts = rootProject.childProjects['grace-shell'].tasks['jar'].outputs.files.collect { "dist/${it.name}" }
    doLast {
        ant.replace(file: file('bin/grace'), token: 'APP_HOME', value: 'GRACE_HOME')
        ant.replace(file: file('bin/grace.bat'), token: 'APP_HOME', value: 'GRACE_HOME')
        ant.replace(file: file('bin/grace'), token: 'media/gradle.icns', value: 'media/icons/grace.icns')
        ant.chmod(file: file('bin/grace'), perm: 'ugo+rx')
    }
}

class GrailsCreateStartScripts extends org.gradle.api.tasks.application.CreateStartScripts {
    @org.gradle.api.tasks.Internal
    Collection<String> projectArtifacts=[]

    @org.gradle.api.tasks.TaskAction
    void generate() {
        def generator = new org.gradle.api.internal.plugins.StartScriptGenerator()
        generator.unixStartScriptGenerator.template = project.rootProject.childProjects['grace-shell'].resources.text.fromFile('src/main/resources/unixStartScript.txt')
        generator.windowsStartScriptGenerator.template = project.rootProject.childProjects['grace-shell'].resources.text.fromFile('src/main/resources/windowsStartScript.txt')
        generator.applicationName = getApplicationName()
        generator.mainClassName = getMainClass().get()
        generator.defaultJvmOpts = getDefaultJvmOpts()
        generator.optsEnvironmentVar = getOptsEnvironmentVar()
        generator.exitEnvironmentVar = getExitEnvironmentVar()
        generator.classpath = projectArtifacts + getClasspath().resolvedConfiguration.resolvedArtifacts.collect { artifact ->
            def dependency = artifact.moduleVersion.id
            String installedFile = "lib/$dependency.group/$dependency.name/jars/$artifact.file.name"
            if (dependency.group == 'org.graceframework') {
                installedFile = "dist/$artifact.file.name"
            }
            installedFile
        }
        generator.scriptRelPath = "bin/${getUnixScript().name}"
        generator.generateUnixScript(getUnixScript())
        generator.generateWindowsScript(getWindowsScript())
    }
}

task install(dependsOn: populateDependencies) { task ->
    subprojects { Project project ->
        if(project.name != 'docs' && !project.name.startsWith('grace-test-suite')) {
            task.dependsOn("$project.name:publishToMavenLocal")
        }
    }
}

task publishToDist { task ->
    subprojects { Project project ->
        if (project.name != 'docs' && !project.name.startsWith('grace-test-suite') && !project.name.startsWith('grace-dependencies') && !project.name.startsWith('grace-bom')) {
            project.tasks.named("generateMetadataFileForIvyPublication").configure {
                enabled = false
            }
            task.dependsOn("$project.name:publishAllPublicationsToGraceDistRepository")
        }
    }
}

task binZip(type: Zip, dependsOn: [publishToDist, populateDependencies, grailsCreateStartScripts]) {
    destinationDirectory = "${buildDir}/distributions" as File
    archiveBaseName = 'grace'
    archiveAppendix = grailsVersion
    archiveClassifier = 'bin'

    into("grace-$grailsVersion") {
        from(projectDir) {
            include 'bin/grace', 'bin/grace.bat', 'LICENSE.txt', 'INSTALL.txt'
        }
        from("lib") {
            into "lib"
            exclude "org.graceframework/**"
        }
        from("lib/org.graceframework") {
            into "dist"
            include '**/*.jar'
        }
        from(homeDistDir) {
            into "dist"
            include "grace-shell-*.jar"
            exclude "*.zip*"
            exclude "*.tar*"
            exclude '*-javadoc.jar*', '*-sources.jar*', 'ivy-*', '*.jar.sha*'
        }
    }
}

task sourcesZip(type: Zip, dependsOn: [publishToDist]) {
    destinationDirectory = "${buildDir}/distributions" as File
    archiveBaseName = 'grace'
    archiveAppendix = grailsVersion
    archiveClassifier = 'sources'

    into("grace-$grailsVersion") {
        from(projectDir) {
            include 'LICENSE.txt'
        }
        from(homeDistDir) {
            into "src"
            include '*-sources.jar', '*-sources.jar.sha*'
        }
    }
}

task docsZip(type: Zip, dependsOn: ['docs:docs']) {
    destinationDirectory = "${buildDir}/distributions" as File
    archiveBaseName = 'grace'
    archiveAppendix = grailsVersion
    archiveClassifier = 'docs'

    into("grace-$grailsVersion") {
        from(projectDir) {
            include 'LICENSE.txt'
        }
        from("$projectDir/docs/build/docs/manual") {
            into "docs"
        }
    }
}

task zipDist(dependsOn: [binZip, sourcesZip, docsZip])

task assemble(dependsOn: [install, zipDist])
