[plugins]
cache = "5.0.0-SNAPSHOT"
fields = "5.0.0"
hibernate5 = "2022.0.0"
scaffolding = "5.0.0"

[profiles]
base = "2022.0.0-SNAPSHOT"
plugin = "2022.0.0-SNAPSHOT"
profile = "2022.0.0-SNAPSHOT"
rest-api = "2022.0.0-SNAPSHOT"
web = "2022.0.0-SNAPSHOT"
web-bootstrap = "2022.0.0-SNAPSHOT"
web-plugin = "2022.0.0-SNAPSHOT"