[plugins]
asset-pipeline = "5.2.7"
cache = "5.2.7"
database-migration = "5.2.7"
fields = "5.2.7"
geb = "5.2.7"
hibernate5 = "2022.2.7"
scaffolding = "5.2.7"

[profiles]
base = "2022.2.7"
plugin = "2022.2.7"
profile = "2022.2.7"
rest-api = "2022.2.7"
web = "2022.2.6"
web-plugin = "2022.2.6"
