[plugins]
asset-pipeline = "5.2.0"
cache = "5.2.0"
database-migration = "5.1.2"
fields = "5.2.0"
geb = "5.1.2"
hibernate5 = "2022.2.0"
scaffolding = "5.2.0"

[profiles]
base = "2022.2.0-SNAPSHOT"
plugin = "2022.2.0-SNAPSHOT"
profile = "2022.2.0-SNAPSHOT"
rest-api = "2022.2.0-SNAPSHOT"
web = "2022.2.0-SNAPSHOT"
web-plugin = "2022.2.0-SNAPSHOT"
