[plugins]
asset-pipeline = "6.1.0-M1"
cache = "6.1.0-SNAPSHOT"
database-migration = "6.1.0-SNAPSHOT"
fields = "6.1.0-SNAPSHOT"
geb = "6.1.0-SNAPSHOT"
hibernate = "2023.1.0-SNAPSHOT"
scaffolding = "6.1.0-SNAPSHOT"

[profiles]
base = "2023.1.0-M1"
plugin = "2023.1.0-M1"
profile = "2023.1.0-M1"
rest-api = "2023.1.0-M1"
starter = "2023.1.0-M1"
web = "2023.1.0-M1"
web-plugin = "2023.1.0-M1"
