[plugins]
asset-pipeline = "5.1.3"
cache = "5.1.3"
database-migration = "5.1.2"
fields = "5.1.2"
geb = "5.1.2"
hibernate5 = "2022.1.3"
scaffolding = "5.1.3"

[profiles]
base = "2022.1.2"
plugin = "2022.1.2"
profile = "2022.1.2"
rest-api = "2022.1.2"
web = "2022.1.2"
web-plugin = "2022.1.2"
