[plugins]
asset-pipeline = "5.2.4"
cache = "5.2.4"
database-migration = "5.2.4"
fields = "5.2.4"
geb = "5.2.4"
hibernate5 = "2022.2.4"
scaffolding = "5.2.4"

[profiles]
base = "2022.2.4"
plugin = "2022.2.4"
profile = "2022.2.4"
rest-api = "2022.2.4"
web = "2022.2.3"
web-plugin = "2022.2.3"
