[plugins]
cache = "5.0.1"
fields = "5.0.0"
geb = "3.0.0"
hibernate5 = "2022.0.1"
mongodb = "7.2.1"
neo4j = "7.2.1"
rxjava = "1.1.1"
rxjava2 = "2.0.0"
scaffolding = "5.0.0"

[profiles]
angular = "8.0.1"
base = "5.0.6"
plugin = "5.0.1"
profile = "5.0.2"
react = "5.0.2"
rest-api = "5.0.1"
rest-api-plugin = "5.0.1"
vue = "5.0.2"
web = "5.0.5"
web-bootstrap = "2022.0.0"
web-clean = "2022.0.0"
web-plugin = "4.0.1"