[plugins]
asset-pipeline = "6.2.0"
cache = "6.2.0"
database-migration = "6.2.0"
fields = "6.2.0"
geb = "6.2.0"
hibernate = "2023.2.0"
scaffolding = "6.2.0"

[profiles]
base = "2023.3.0-M1"
plugin = "2023.3.0-M1"
profile = "2023.3.0-M1"
rest-api = "2023.3.0-M1"
starter = "2023.3.0-M1"
web = "2023.3.0-M1"
web-plugin = "2023.2.0"
