[plugins]
cache = "5.1.1"
database-migration = "5.1.1"
geb = "5.1.0"
fields = "5.1.1"
hibernate5 = "2022.1.1"
scaffolding = "5.1.1"

[profiles]
base = "2022.1.1"
plugin = "2022.1.1"
profile = "2022.1.1"
rest-api = "2022.1.1"
web = "2022.1.1"
web-plugin = "2022.1.1"
