[plugins]
asset-pipeline = "5.2.5"
cache = "5.2.5"
database-migration = "5.2.5"
fields = "5.2.5"
geb = "5.2.4"
hibernate5 = "2022.2.5"
scaffolding = "5.2.5"

[profiles]
base = "2022.2.4"
plugin = "2022.2.4"
profile = "2022.2.4"
rest-api = "2022.2.4"
web = "2022.2.4"
web-plugin = "2022.2.4"
