[plugins]
cache = "5.0.1"
database-migration = "5.0.1"
geb = "5.0.1"
fields = "5.0.1"
hibernate5 = "2022.0.1"
scaffolding = "5.0.1"

[profiles]
base = "2022.0.2"
plugin = "2022.0.0"
profile = "2022.0.0"
rest-api = "2022.0.0"
web = "2022.0.0"
web-plugin = "2022.0.0"
