[plugins]
asset-pipeline = "5.1.2"
cache = "6.0.0-SNAPSHOT"
database-migration = "5.1.2"
fields = "6.0.0-SNAPSHOT"
geb = "5.1.2"
hibernate5 = "2022.1.2"
scaffolding = "6.0.0-SNAPSHOT"

[profiles]
base = "2022.2.0-SNAPSHOT"
plugin = "2022.2.0-SNAPSHOT"
profile = "2022.2.0-SNAPSHOT"
rest-api = "2022.2.0-SNAPSHOT"
web = "2022.2.0-SNAPSHOT"
web-plugin = "2022.2.0-SNAPSHOT"
