[plugins]
asset-pipeline = "5.2.7"
cache = "5.2.6"
database-migration = "5.2.6"
fields = "5.2.6"
geb = "5.2.6"
hibernate5 = "2022.2.6"
scaffolding = "5.2.6"

[profiles]
base = "2022.2.6"
plugin = "2022.2.6"
profile = "2022.2.6"
rest-api = "2022.2.6"
web = "2022.2.6"
web-plugin = "2022.2.6"
