[plugins]
asset-pipeline = "6.0.1"
cache = "6.0.1"
database-migration = "6.0.0"
fields = "6.0.0"
geb = "6.0.0"
hibernate = "2023.0.0"
scaffolding = "6.0.0"

[profiles]
base = "2023.0.0"
plugin = "2023.0.0"
profile = "2023.0.0"
rest-api = "2023.0.0"
starter = "2023.0.0"
web = "2023.0.0"
web-plugin = "2023.0.0"
