[plugins]
asset-pipeline = "5.1.3"
cache = "5.1.3"
database-migration = "5.1.3"
fields = "5.1.3"
geb = "5.1.3"
hibernate5 = "2022.1.4"
scaffolding = "5.1.4"

[profiles]
base = "2022.1.3"
plugin = "2022.1.3"
profile = "2022.1.3"
rest-api = "2022.1.3"
web = "2022.1.3"
web-plugin = "2022.1.3"
