[plugins]
asset-pipeline = "6.1.0-SNAPSHOT"
cache = "6.0.1"
database-migration = "6.0.1"
fields = "6.0.1"
geb = "6.0.1"
hibernate = "2023.1.0-SNAPSHOT"
scaffolding = "6.1.0-SNAPSHOT"

[profiles]
base = "2023.1.0-SNAPSHOT"
plugin = "2023.1.0-SNAPSHOT"
profile = "2023.1.0-SNAPSHOT"
rest-api = "2023.1.0-SNAPSHOT"
starter = "2023.1.0-SNAPSHOT"
web = "2023.1.0-SNAPSHOT"
web-plugin = "2023.1.0-SNAPSHOT"
