[plugins]
asset-pipeline = "5.2.3"
cache = "5.2.3"
database-migration = "5.2.3"
fields = "5.2.3"
geb = "5.2.3"
hibernate5 = "2022.2.4"
scaffolding = "5.2.3"

[profiles]
base = "2022.2.3"
plugin = "2022.2.3"
profile = "2022.2.3"
rest-api = "2022.2.3"
web = "2022.2.3"
web-plugin = "2022.2.3"
