[plugins]
asset-pipeline = "6.2.0-M2"
cache = "6.2.0-M1"
database-migration = "6.2.0-M1"
fields = "6.2.0-M1"
geb = "6.2.0-M1"
hibernate = "2023.2.0-M1"
scaffolding = "6.2.0-M1"

[profiles]
base = "2023.2.0-M2"
plugin = "2023.2.0-M2"
profile = "2023.2.0-M2"
rest-api = "2023.2.0-M2"
starter = "2023.2.0-M2"
web = "2023.2.0-M2"
web-plugin = "2023.2.0-M2"
