[plugins]
asset-pipeline = "5.2.1"
cache = "5.2.1"
database-migration = "5.2.1"
fields = "5.2.1"
geb = "5.2.1"
hibernate5 = "2023.0.0-M1"
scaffolding = "5.2.1"

[profiles]
base = "2022.2.1"
plugin = "2022.2.1"
profile = "2022.2.1"
rest-api = "2022.2.1"
web = "2022.2.1"
web-plugin = "2022.2.1"
