[plugins]
asset-pipeline = "6.1.0-M2"
cache = "6.1.0-M2"
database-migration = "6.1.0-M2"
fields = "6.1.0-M2"
geb = "6.1.0-M2"
hibernate = "2023.1.0-M2"
scaffolding = "6.1.0-M2"

[profiles]
base = "2023.1.0-M2"
plugin = "2023.1.0-M2"
profile = "2023.1.0-M2"
rest-api = "2023.1.0-M2"
starter = "2023.1.0-M2"
web = "2023.1.0-M2"
web-plugin = "2023.1.0-M2"
