[plugins]
asset-pipeline = "6.3.0-M1"
cache = "6.3.0-M1"
database-migration = "6.3.0-SNAPSHOT"
fields = "6.2.0"
geb = "6.2.0"
hibernate = "2023.3.0-SNAPSHOT"
scaffolding = "6.2.0"

[profiles]
base = "2023.3.0-SNAPSHOT"
plugin = "2023.3.0-SNAPSHOT"
profile = "2023.3.0-SNAPSHOT"
rest-api = "2023.3.0-SNAPSHOT"
starter = "2023.3.0-SNAPSHOT"
web = "2023.3.0-SNAPSHOT"
web-plugin = "2023.3.0-SNAPSHOT"
