[plugins]
asset-pipeline = "6.0.0-M4"
cache = "6.0.0-M3"
database-migration = "6.0.0-M3"
fields = "6.0.0-M3"
geb = "6.0.0-M3"
hibernate = "2023.0.0-M5"
scaffolding = "6.0.0-M3"

[profiles]
base = "2023.0.0-M4"
plugin = "2023.0.0-M3"
profile = "2023.0.0-M3"
rest-api = "2023.0.0-M3"
web = "2023.0.0-M3"
web-plugin = "2023.0.0-M3"
