[plugins]
asset-pipeline = "6.0.0-M2"
cache = "6.0.0-M1"
database-migration = "6.0.0-M1"
fields = "6.0.0-M1"
geb = "6.0.0-M1"
hibernate5 = "2023.0.0-M3"
scaffolding = "6.0.0-M1"

[profiles]
base = "2023.0.0-M2"
plugin = "2023.0.0-M1"
profile = "2023.0.0-M1"
rest-api = "2023.0.0-M1"
web = "2022.2.1"
web-plugin = "2023.0.0-M1"
