[plugins]
cache = "5.0.1"
fields = "5.0.0-SNAPSHOT"
geb = "3.0.0"
gorm-hibernate5 = "7.2.3-SNAPSHOT"
gorm-mongodb = "7.2.1"
gorm-neo4j = "7.2.1"
grails-gradle-plugin = "22.0.0-SNAPSHOT"
rxjava = "1.1.1"
rxjava2 = "2.0.0"
scaffolding = "5.0.0-SNAPSHOT"
views-json = "2.2.2-SNAPSHOT"
views-json-templates = "2.2.2-SNAPSHOT"
views-markup = "2.2.2-SNAPSHOT"

[profiles]
angular = "8.0.1"
base = "5.0.6"
plugin = "5.0.1"
profile = "5.0.2"
react = "5.0.0"
rest-api = "5.0.1"
rest-api-plugin = "5.0.1"
vue = "5.0.0"
web = "5.0.4"
web-bootstrap = "5.0.0-SNAPSHOT"
web-clean = "5.0.0-SNAPSHOT"
web-plugin = "4.0.1"