[plugins]
cache = "5.1.0"
database-migration = "5.1.0"
geb = "5.1.0"
fields = "5.1.0"
hibernate5 = "2022.1.0"
scaffolding = "5.1.0"

[profiles]
base = "2022.1.0"
plugin = "2022.1.0"
profile = "2022.1.0"
rest-api = "2022.1.0"
web = "2022.1.0"
web-plugin = "2022.1.0"
