[plugins]
asset-pipeline = "6.0.0-RC1"
cache = "6.0.0-M3"
database-migration = "6.0.0-M3"
fields = "6.0.0-M3"
geb = "6.0.0-M3"
hibernate = "2023.0.0-M5"
scaffolding = "6.0.0-M3"

[profiles]
base = "2023.0.0-SNAPSHOT"
plugin = "2023.0.0-M4"
profile = "2023.0.0-M4"
rest-api = "2023.0.0-M4"
starter = "2023.0.0-M1"
web = "2023.0.0-SNAPSHOT"
web-plugin = "2023.0.0-M4"
