[plugins]
asset-pipeline = "6.1.0-M2"
cache = "6.1.0-M2"
database-migration = "6.1.0-SNAPSHOT"
fields = "6.1.0-SNAPSHOT"
geb = "6.1.0-M2"
hibernate = "2023.1.0-SNAPSHOT"
scaffolding = "6.1.0-M2"

[profiles]
base = "2023.1.0-SNAPSHOT"
plugin = "2023.1.0-SNAPSHOT"
profile = "2023.1.0-SNAPSHOT"
rest-api = "2023.1.0-SNAPSHOT"
starter = "2023.1.0-SNAPSHOT"
web = "2023.1.0-SNAPSHOT"
web-plugin = "2023.1.0-SNAPSHOT"
