[plugins]
asset-pipeline = "6.0.0-RC1"
cache = "6.0.0-RC1"
database-migration = "6.0.0-RC1"
fields = "6.0.0-SNAPSHOT"
geb = "6.0.0-RC1"
hibernate = "2023.0.0"
scaffolding = "6.0.0-SNAPSHOT"

[profiles]
base = "2023.0.0-SNAPSHOT"
plugin = "2023.0.0-RC2"
profile = "2023.0.0-RC2"
rest-api = "2023.0.0-RC2"
starter = "2023.0.0-RC2"
web = "2023.0.0-SNAPSHOT"
web-plugin = "2023.0.0-RC2"
