[versions]
ant = "1.10.15"
asciidoctorj = "2.5.13"
aspectj = "1.9.24"
assertj = "3.26.3"
bytebuddy = "1.15.11"
caffeine = "3.1.8"
cglib = "3.3.0"
commons-codec = "1.17.2"
commons-lang = "2.6"
commons-lang3 = "3.17.0"
commons-text = "1.13.1"
commons-validator = "1.9.0"
glassfish-web-jsp-jstl = "3.0.1"
gpars = "1.2.1"
gradle = "8.14.3"
gradle-git-properties = "2.4.2"
grace-async = "7.0.0-M1"
grace-events = "7.0.0-SNAPSHOT"
grace-data = "2024.0.0-SNAPSHOT"
grace-data-hibernate = "2024.0.0-SNAPSHOT"
grace-data-mongodb = "2024.0.0-SNAPSHOT"
grace-doc-engine = "2.0.0-M1"
groovy = "4.0.29"
gson = "2.11.0"
h2 = "2.3.232"
hsqldb = "2.7.3"
itext = "2.0.8"
jackson-databind = "2.18.4"
jansi = "1.18"
jakarta-annotation = "2.1.1"
jakarta-el = "5.0.1"
jakarta-inject = "2.0.1"
jakarta-persistence = "3.1.0"
jakarta-servlet = "6.0.0"
jakarta-servlet-jsp = "3.1.1"
jakarta-servlet-jsp-jstl = "3.0.2"
jakarta-transaction = "2.0.1"
jakarta-validation = "3.0.2"
jakarta-xml-bind = "4.0.2"
javaparser = "3.26.4"
javassist = "3.30.2-GA"
jline = "2.14.6"
jodd = "3.3.8"
json-unit = "2.40.1"
jsoup = "1.18.3"
jsr305 = "3.0.2"
junit-jupiter = "5.11.4"
junit-platform = "1.11.4"
liquibase = "4.27.0"
maven = "3.9.11"
maven-resolver = "1.9.24"
mockito = "5.14.2"
objenesis = "3.4"
rxjava = "1.3.8"
rxjava2 = "2.2.21"
rxjava3 = "3.1.12"
sitemesh = "2.6.0"
slf4j = "2.0.17"
snakeyaml = "2.3"
spock = "2.3-groovy-4.0"
spring-boot = "3.4.11"
spring-dependency-management = "1.1.7"
spring-framework = "6.2.12"
tomcat = "10.1.48"
xhtmlrenderer = "R8"

[libraries]
ant = { module = "org.apache.ant:ant", version.ref = "ant" }
ant-junit = { module = "org.apache.ant:ant-junit", version.ref = "ant" }
asciidoctorj = { module = "org.asciidoctor:asciidoctorj", version.ref = "asciidoctorj" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
aspectj-rt = { module = "org.aspectj:aspectjrt", version.ref = "aspectj" }
aspectj-weaver = { module = "org.aspectj:aspectjweaver", version.ref = "aspectj" }
bytebuddy = { module = "net.bytebuddy:byte-buddy", version.ref = "bytebuddy" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
cglib = { module = "cglib:cglib-nodep", version.ref = "cglib" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
commons-lang = { module = "commons-lang:commons-lang", version.ref = "commons-lang" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
commons-validator = { module = "commons-validator:commons-validator", version.ref = "commons-validator" }
glassfish-web-jsp-jstl = { module = "org.glassfish.web:jakarta.servlet.jsp.jstl", version.ref = "glassfish-web-jsp-jstl" }
gpars = { module = "org.codehaus.gpars:gpars", version.ref = "gpars" }
gradle-tooling-api = { module = "org.gradle:gradle-tooling-api", version.ref = "gradle" }
grace-async-core = { module = "org.graceframework.async:grace-async-core", version.ref = "grace-async" }
grace-async-gpars = { module = "org.graceframework.async:grace-async-gpars", version.ref = "grace-async" }
grace-async-rxjava = { module = "org.graceframework.async:grace-async-rxjava", version.ref = "grace-async" }
grace-async-rxjava2 = { module = "org.graceframework.async:grace-async-rxjava2", version.ref = "grace-async" }
grace-async-rxjava3 = { module = "org.graceframework.async:grace-async-rxjava3", version.ref = "grace-async" }
grace-events-core = { module = "org.graceframework.events:grace-events-core", version.ref = "grace-events" }
grace-events-gpars = { module = "org.graceframework.events:grace-events-gpars", version.ref = "grace-events" }
grace-events-rxjava = { module = "org.graceframework.events:grace-events-rxjava", version.ref = "grace-events" }
grace-events-rxjava2 = { module = "org.graceframework.events:grace-events-rxjava2", version.ref = "grace-events" }
grace-events-rxjava3 = { module = "org.graceframework.events:grace-events-rxjava3", version.ref = "grace-events" }
grace-events-spring = { module = "org.graceframework.events:grace-events-spring", version.ref = "grace-events" }
grace-events-transform = { module = "org.graceframework.events:grace-events-transform", version.ref = "grace-events" }
grace-datastore-core = { module = "org.graceframework:grace-datastore-core", version.ref = "grace-data" }
grace-datastore-gorm = { module = "org.graceframework:grace-datastore-gorm", version.ref = "grace-data" }
grace-datastore-gorm-async = { module = "org.graceframework:grace-datastore-gorm-async", version.ref = "grace-data" }
grace-datastore-gorm-bson = { module = "org.graceframework:grace-datastore-gorm-bson", version.ref = "grace-data-mongodb" }
grace-datastore-gorm-hibernate = { module = "org.graceframework:grace-datastore-gorm-hibernate", version.ref = "grace-data-hibernate" }
grace-datastore-gorm-mongodb = { module = "org.graceframework:grace-datastore-gorm-mongodb", version.ref = "grace-data-mongodb" }
grace-datastore-gorm-mongodb-ext = { module = "org.graceframework:grace-datastore-gorm-mongodb-ext", version.ref = "grace-data-mongodb" }
grace-datastore-gorm-support = { module = "org.graceframework:grace-datastore-gorm-support", version.ref = "grace-data" }
grace-datastore-gorm-tck = { module = "org.graceframework:grace-datastore-gorm-tck", version.ref = "grace-data" }
grace-datastore-gorm-test = { module = "org.graceframework:grace-datastore-gorm-test", version.ref = "grace-data" }
grace-datastore-gorm-validation = { module = "org.graceframework:grace-datastore-gorm-validation", version.ref = "grace-data" }
grace-datastore-web = { module = "org.graceframework:grace-datastore-web", version.ref = "grace-data" }
grace-doc-engine = { module = "org.graceframework:grace-doc-engine", version.ref = "grace-doc-engine" }
groovy-ant = { module = "org.apache.groovy:groovy-ant", version.ref = "groovy" }
groovy-bom = { module = "org.apache.groovy:groovy-bom", version.ref = "groovy" }
groovy-console = { module = "org.apache.groovy:groovy-console", version.ref = "groovy" }
groovy-core = { module = "org.apache.groovy:groovy", version.ref = "groovy" }
groovy-dateutil = { module = "org.apache.groovy:groovy-dateutil", version.ref = "groovy" }
groovy-groovydoc = { module = "org.apache.groovy:groovy-groovydoc", version.ref = "groovy" }
groovy-groovysh = { module = "org.apache.groovy:groovy-groovysh", version.ref = "groovy" }
groovy-jmx = { module = "org.apache.groovy:groovy-jmx", version.ref = "groovy" }
groovy-json = { module = "org.apache.groovy:groovy-json", version.ref = "groovy" }
groovy-macro = { module = "org.apache.groovy:groovy-macro", version.ref = "groovy" }
groovy-nio = { module = "org.apache.groovy:groovy-nio", version.ref = "groovy" }
groovy-picocli = { module = "org.apache.groovy:groovy-cli-picocli", version.ref = "groovy" }
groovy-sql = { module = "org.apache.groovy:groovy-sql", version.ref = "groovy" }
groovy-swing = { module = "org.apache.groovy:groovy-swing", version.ref = "groovy" }
groovy-templates = { module = "org.apache.groovy:groovy-templates", version.ref = "groovy" }
groovy-test = { module = "org.apache.groovy:groovy-test", version.ref = "groovy" }
groovy-test-junit5 = { module = "org.apache.groovy:groovy-test-junit5", version.ref = "groovy" }
groovy-toml = { module = "org.apache.groovy:groovy-toml", version.ref = "groovy" }
groovy-xml = { module = "org.apache.groovy:groovy-xml", version.ref = "groovy" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
hsqldb = { module = "org.hsqldb:hsqldb", version.ref = "hsqldb" }
itext = { module = "com.lowagie:itext", version.ref = "itext" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-databind" }
jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation" }
jakarta-el = { module = "jakarta.el:jakarta.el-api", version.ref = "jakarta-el" }
jakarta-inject = { module = "jakarta.inject:jakarta.inject-api", version.ref = "jakarta-inject" }
jakarta-persistence-api = { module = "jakarta.persistence:jakarta.persistence-api", version.ref = "jakarta-persistence" }
jakarta-servlet = { module = "jakarta.servlet:jakarta.servlet-api", version.ref = "jakarta-servlet" }
jakarta-servlet-jsp = { module = "jakarta.servlet.jsp:jakarta.servlet.jsp-api", version.ref = "jakarta-servlet-jsp" }
jakarta-servlet-jsp-jstl = { module = "jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api", version.ref = "jakarta-servlet-jsp-jstl" }
jakarta-transaction = { module = "jakarta.transaction:jakarta.transaction-api", version.ref = "jakarta-transaction" }
jakarta-validation = { module = "jakarta.validation:jakarta.validation-api", version.ref = "jakarta-validation" }
jakarta-xml-bind-api = { module = "jakarta.xml.bind:jakarta.xml.bind-api", version.ref = "jakarta-xml-bind" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
javaparser = { module = "com.github.javaparser:javaparser-core", version.ref = "javaparser" }
javassist = { module = "org.javassist:javassist", version.ref = "javassist" }
jline = { module = "jline:jline", version.ref = "jline" }
jodd-wot = { module = "org.jodd:jodd-wot", version.ref = "jodd" }
json-unit = { module = "net.javacrumbs.json-unit:json-unit", version.ref = "json-unit" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-engine", version.ref = "junit-platform" }
junit-platform-runner = { module = "org.junit.platform:junit-platform-runner", version.ref = "junit-platform" }
liquibase-cdi = { module = "org.liquibase:liquibase-cdi", version.ref = "liquibase" }
liquibase-core = { module = "org.liquibase:liquibase-core", version.ref = "liquibase" }
liquibase-hibernate = { module = "org.liquibase.ext:liquibase-hibernate5", version.ref = "liquibase" }
maven-model = { module = "org.apache.maven:maven-model", version.ref = "maven" }
maven-resolver-connectorBasic = { module = "org.apache.maven.resolver:maven-resolver-connector-basic", version.ref = "maven-resolver" }
maven-resolver-provider = { module = "org.apache.maven:maven-resolver-provider", version.ref = "maven" }
maven-resolver-impl = { module = "org.apache.maven.resolver:maven-resolver-impl", version.ref = "maven-resolver" }
maven-resolver-transportFile = { module = "org.apache.maven.resolver:maven-resolver-transport-file", version.ref = "maven-resolver" }
maven-resolver-transportHttp = { module = "org.apache.maven.resolver:maven-resolver-transport-http", version.ref = "maven-resolver" }
maven-settings-builder = { module = "org.apache.maven:maven-settings-builder", version.ref = "maven" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
objenesis = { module = "org.objenesis:objenesis", version.ref = "objenesis" }
rxjava = { module = "io.reactivex:rxjava", version.ref = "rxjava" }
rxjava2 = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava2" }
rxjava3 = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava3" }
sitemesh = { module = "opensymphony:sitemesh", version.ref = "sitemesh" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-jcl = { module = "org.slf4j:jcl-over-slf4j", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
spock-spring = { module = "org.spockframework:spock-spring", version.ref = "spock" }
spring-aop = { module = "org.springframework:spring-aop", version.ref = "spring-framework" }
spring-aspects = { module = "org.springframework:spring-aspects", version.ref = "spring-framework" }
spring-beans = { module = "org.springframework:spring-beans", version.ref = "spring-framework" }
spring-boot = { module = "org.springframework.boot:spring-boot", version.ref = "spring-boot" }
spring-boot-actuator-autoconfigure = { module = "org.springframework.boot:spring-boot-actuator-autoconfigure", version.ref = "spring-boot" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring-boot" }
spring-boot-autoconfigureProcessor = { module = "org.springframework.boot:spring-boot-autoconfigure-processor", version.ref = "spring-boot" }
spring-boot-cli = { module = "org.springframework.boot:spring-boot-cli", version.ref = "spring-boot" }
spring-boot-configurationProcessor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "spring-boot" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "spring-boot" }
spring-boot-gradle-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }
spring-boot-loader-tools = { module = "org.springframework.boot:spring-boot-loader-tools", version.ref = "spring-boot" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-json = { module = "org.springframework.boot:spring-boot-starter-json", version.ref = "spring-boot" }
spring-boot-starter-tomcat = { module = "org.springframework.boot:spring-boot-starter-tomcat", version.ref = "spring-boot" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-test", version.ref = "spring-boot" }
spring-context = { module = "org.springframework:spring-context", version.ref = "spring-framework" }
spring-contextSupport = { module = "org.springframework:spring-context-support", version.ref = "spring-framework" }
spring-core = { module = "org.springframework:spring-core", version.ref = "spring-framework" }
spring-dependency-management-plugin = { module = "io.spring.gradle:dependency-management-plugin", version.ref = "spring-dependency-management" }
spring-framework-bom = { module = "org.springframework:spring-framework-bom", version.ref = "spring-framework" }
spring-jdbc = { module = "org.springframework:spring-jdbc", version.ref = "spring-framework" }
spring-test = { module = "org.springframework:spring-test", version.ref = "spring-framework" }
spring-tx = { module = "org.springframework:spring-tx", version.ref = "spring-framework" }
spring-web = { module = "org.springframework:spring-web", version.ref = "spring-framework" }
spring-webmvc = { module = "org.springframework:spring-webmvc", version.ref = "spring-framework" }
spring-websocket = { module = "org.springframework:spring-websocket", version.ref = "spring-framework" }
tomcat-annotations-api = { module = "org.apache.tomcat:tomcat-annotations-api", version.ref = "tomcat" }
tomcat-jdbc = { module = "org.apache.tomcat:tomcat-jdbc", version.ref = "tomcat" }
tomcat-jsp-api = { module = "org.apache.tomcat:tomcat-jsp-api", version.ref = "tomcat" }
tomcat-embed-core = { module = "org.apache.tomcat.embed:tomcat-embed-core", version.ref = "tomcat" }
tomcat-embed-el = { module = "org.apache.tomcat.embed:tomcat-embed-el", version.ref = "tomcat" }
tomcat-embed-jasper = { module = "org.apache.tomcat.embed:tomcat-embed-jasper", version.ref = "tomcat" }
tomcat-embed-websocket = { module = "org.apache.tomcat.embed:tomcat-embed-websocket", version.ref = "tomcat" }
xhtmlrenderer = { module = "org.xhtmlrenderer:core-renderer", version.ref = "xhtmlrenderer" }

[bundles]
boms = ["groovy-bom", "spring-framework-bom", "spring-boot-dependencies"]
grace-async-bundle = ["grace-async-core", "grace-async-gpars", "grace-async-rxjava", "grace-async-rxjava2", "grace-async-rxjava3"]
grace-dependencies-bundle = ["commons-text", "commons-validator", "gpars", "rxjava", "rxjava2", "rxjava3"]
grace-events-bundle = ["grace-events-core", "grace-events-gpars", "grace-events-rxjava", "grace-events-rxjava2", "grace-events-rxjava3", "grace-events-spring", "grace-events-transform"]
grace-data-bundle = ["grace-datastore-core", "grace-datastore-gorm", "grace-datastore-gorm-async", "grace-datastore-gorm-bson", "grace-datastore-gorm-hibernate", "grace-datastore-gorm-mongodb", "grace-datastore-gorm-mongodb-ext", "grace-datastore-gorm-support", "grace-datastore-gorm-tck", "grace-datastore-gorm-test", "grace-datastore-gorm-validation", "grace-datastore-web"]
groovy-bundle = ["groovy-bom"]
h2-bundle = ["h2"]
jakarta-bundle = ["jakarta-annotation-api", "jakarta-el", "jakarta-inject", "jakarta-persistence-api", "jakarta-servlet", "jakarta-servlet-jsp", "jakarta-servlet-jsp-jstl", "jakarta-transaction", "jakarta-validation", "jakarta-xml-bind-api"]
liquibase-bundle = ["liquibase-cdi", "liquibase-core", "liquibase-hibernate"]
spock-bundle = ["spock-core", "spock-spring"]
spring-boot-bundle = ["spring-boot-dependencies"]
spring-framework-bundle = ["spring-framework-bom"]
snakeyaml-bundle = ["snakeyaml"]
tomcat-bundle = ["tomcat-annotations-api", "tomcat-jdbc", "tomcat-jsp-api", "tomcat-embed-core", "tomcat-embed-el", "tomcat-embed-jasper", "tomcat-embed-websocket"]