[versions]
ant = "1.10.12"
asciidoctorj = "2.5.6"
aspectj = "1.9.8"
assertj = "3.22.0"
caffeine = "2.9.3"
cglib = "3.3.0"
commons-codec = "1.15"
commons-lang = "2.6"
commons-lang3 = "3.12.0"
gradle = "7.6.2"
gradle-extra-configurations-plugin = "7.0.0"
gradle-git-properties = "2.4.1"
gradle-nexus-plugin = "2.3.1"
gradle-nexus-publish-plugin = "1.1.0"
grace-async = "5.1.4"
grace-events = "5.1.4"
grails-gdoc = "1.0.1"
grace-gorm = "2022.1.4"
grace-gorm-hibernate = "2022.1.4"
grace-gsp = "2022.1.4"
grace-scaffolding = "5.1.4"
grace-views = "5.1.4"
groovy = "3.0.18"
gson = "2.9.1"
h2 = "2.1.214"
hsqldb = "2.5.2"
itext = "2.0.8"
jackson-databind = "2.13.5"
jansi = "1.18"
jakarta-annotation = "2.0.0"
javaparser = "3.15.14"
javassist = "3.29.0-GA"
javax-annotation = "1.3.2"
javax-el = "2.2"
javax-inject = "1"
javax-jaxb = "2.3.1"
javax-jsp = "2.2"
javax-jstl = "1.2"
javax-persistence = "2.2"
javax-servlet = "4.0.1"
jline = "2.14.6"
json-unit = "2.36.0"
jsoup = "1.15.3"
jsr305 = "3.0.2"
junit-jupiter = "5.8.2"
junit-platform = "1.8.2"
maven = "3.6.3"
maven-resolver = "1.6.3"
methvin-directory-watcher = "0.17.3"
micronaut-cache = "3.5.0"
micronaut-core = "3.8.6"
micronaut-groovy = "3.4.0"
micronaut-spring = "4.5.0"
mockito = "4.5.1"
mongodb-java-driver = "4.6.1"
objenesis = "3.2"
slf4j = "1.7.36"
snakeyaml = "1.33"
spock = "2.3-groovy-3.0"
spring-boot = "2.7.18"
spring-dependency-management = "1.0.15.RELEASE"
spring-framework = "5.3.31"
standard-taglib = "1.2.5"
tomcat = "9.0.83"
xhtmlrenderer = "8.0"

[libraries]
ant = { module = "org.apache.ant:ant", version.ref = "ant" }
ant-junit = { module = "org.apache.ant:ant-junit", version.ref = "ant" }
asciidoctorj = { module = "org.asciidoctor:asciidoctorj", version.ref = "asciidoctorj" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
aspectj-rt = { module = "org.aspectj:aspectjrt", version.ref = "aspectj" }
aspectj-weaver = { module = "org.aspectj:aspectjweaver", version.ref = "aspectj" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
cglib = { module = "cglib:cglib-nodep", version.ref = "cglib" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
commons-lang = { module = "commons-lang:commons-lang", version.ref = "commons-lang" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
gradle-extra-configurations-plugin = { module = "com.netflix.nebula:gradle-extra-configurations-plugin", version.ref = "gradle-extra-configurations-plugin" }
gradle-nexus-plugin = { module = "com.bmuschko:gradle-nexus-plugin", version.ref = "gradle-nexus-plugin" }
gradle-nexus-publish-plugin = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "gradle-nexus-publish-plugin" }
gradle-tooling-api = { module = "org.gradle:gradle-tooling-api", version.ref = "gradle" }
grails-async = { module = "org.graceframework:grace-async", version.ref = "grace-async" }
grails-async-gpars = { module = "org.graceframework:grace-async-gpars", version.ref = "grace-async" }
grails-async-rxjava = { module = "org.graceframework:grace-async-rxjava", version.ref = "grace-async" }
grails-async-rxjava2 = { module = "org.graceframework:grace-async-rxjava2", version.ref = "grace-async" }
grails-events = { module = "org.graceframework:grace-events", version.ref = "grace-events" }
grails-events-compat = { module = "org.graceframework:grace-events-compat", version.ref = "grace-events" }
grails-events-gpars = { module = "org.graceframework:grace-events-gpars", version.ref = "grace-events" }
grails-events-rxjava = { module = "org.graceframework:grace-events-rxjava", version.ref = "grace-events" }
grails-events-rxjava2 = { module = "org.graceframework:grace-events-rxjava2", version.ref = "grace-events" }
grails-events-spring = { module = "org.graceframework:grace-events-spring", version.ref = "grace-events" }
grails-events-transform = { module = "org.graceframework:grace-events-transform", version.ref = "grace-events" }
grails-datastore-core = { module = "org.graceframework:grace-datastore-core", version.ref = "grace-gorm" }
grails-datastore-async = { module = "org.graceframework:grace-datastore-async", version.ref = "grace-gorm" }
grails-datastore-gorm = { module = "org.graceframework:grace-datastore-gorm", version.ref = "grace-gorm" }
grails-datastore-gorm-async = { module = "org.graceframework:grace-datastore-gorm-async", version.ref = "grace-gorm" }
grails-datastore-gorm-hibernate5 = { module = "org.graceframework:grace-datastore-gorm-hibernate5", version.ref = "grace-gorm-hibernate" }
grails-datastore-gorm-support = { module = "org.graceframework:grace-datastore-gorm-support", version.ref = "grace-gorm" }
grails-datastore-gorm-test = { module = "org.graceframework:grace-datastore-gorm-test", version.ref = "grace-gorm" }
grails-datastore-gorm-validation = { module = "org.graceframework:grace-datastore-gorm-validation", version.ref = "grace-gorm" }
grails-datastore-web = { module = "org.graceframework:grace-datastore-web", version.ref = "grace-gorm" }
grails-gdoc-engine = { module = "org.grails:grails-gdoc-engine", version.ref = "grails-gdoc" }
grails-gsp = { module = "org.graceframework:grace-gsp", version.ref = "grace-gsp" }
grails-plugin-async = { module = "org.graceframework.plugins:async", version.ref = "grace-async" }
grails-plugin-gsp = { module = "org.graceframework.plugins:gsp", version.ref = "grace-gsp" }
grails-plugin-events = { module = "org.graceframework.plugins:events", version.ref = "grace-events" }
grails-scaffolding-core = { module = "org.graceframework:grace-scaffolding-core", version.ref = "grace-scaffolding" }
grails-taglib = { module = "org.graceframework:grace-taglib", version.ref = "grace-gsp" }
grails-views-core = { module = "org.graceframework:views-core", version.ref = "grace-views" }
grails-views-gradle = { module = "org.graceframework.plugins:views-gradle", version.ref = "grace-views" }
grails-views-json = { module = "org.graceframework.plugins:views-json", version.ref = "grace-views" }
grails-views-json-templates = { module = "org.graceframework.plugins:views-json-templates", version.ref = "grace-views" }
grails-views-json-testing-support = { module = "org.graceframework:views-json-testing-support", version.ref = "grace-views" }
grails-views-markup = { module = "org.graceframework.plugins:views-markup", version.ref = "grace-views" }
grails-web-gsp = { module = "org.graceframework:grace-web-gsp", version.ref = "grace-gsp" }
grails-web-gsp-taglib = { module = "org.graceframework:grace-web-gsp-taglib", version.ref = "grace-gsp" }
grails-web-jsp = { module = "org.graceframework:grace-web-jsp", version.ref = "grace-gsp" }
grails-web-sitemesh = { module = "org.graceframework:grace-web-sitemesh", version.ref = "grace-gsp" }
grails-web-taglib = { module = "org.graceframework:grace-web-taglib", version.ref = "grace-gsp" }
groovy-ant = { module = "org.codehaus.groovy:groovy-ant", version.ref = "groovy" }
groovy-bom = { module = "org.codehaus.groovy:groovy-bom", version.ref = "groovy" }
groovy-console = { module = "org.codehaus.groovy:groovy-console", version.ref = "groovy" }
groovy-core = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
groovy-dateutil = { module = "org.codehaus.groovy:groovy-dateutil", version.ref = "groovy" }
groovy-groovydoc = { module = "org.codehaus.groovy:groovy-groovydoc", version.ref = "groovy" }
groovy-groovysh = { module = "org.codehaus.groovy:groovy-groovysh", version.ref = "groovy" }
groovy-jmx = { module = "org.codehaus.groovy:groovy-jmx", version.ref = "groovy" }
groovy-json = { module = "org.codehaus.groovy:groovy-json", version.ref = "groovy" }
groovy-macro = { module = "org.codehaus.groovy:groovy-macro", version.ref = "groovy" }
groovy-nio = { module = "org.codehaus.groovy:groovy-nio", version.ref = "groovy" }
groovy-picocli = { module = "org.codehaus.groovy:groovy-cli-picocli", version.ref = "groovy" }
groovy-sql = { module = "org.codehaus.groovy:groovy-sql", version.ref = "groovy" }
groovy-swing = { module = "org.codehaus.groovy:groovy-swing", version.ref = "groovy" }
groovy-templates = { module = "org.codehaus.groovy:groovy-templates", version.ref = "groovy" }
groovy-test = { module = "org.codehaus.groovy:groovy-test", version.ref = "groovy" }
groovy-test-junit5 = { module = "org.codehaus.groovy:groovy-test-junit5", version.ref = "groovy" }
groovy-xml = { module = "org.codehaus.groovy:groovy-xml", version.ref = "groovy" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
hsqldb = { module = "org.hsqldb:hsqldb", version.ref = "hsqldb" }
itext = { module = "com.lowagie:itext", version.ref = "itext" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-databind" }
jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
javaparser = { module = "com.github.javaparser:javaparser-core", version.ref = "javaparser" }
javassist = { module = "org.javassist:javassist", version.ref = "javassist" }
javax-annotation = { module = "javax.annotation:javax.annotation-api", version.ref = "javax-annotation" }
javax-el = { module = "javax.el:el-api", version.ref = "javax-el" }
javax-jaxb-api = { module = "javax.xml.bind:jaxb-api", version.ref = "javax-jaxb" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject" }
javax-jsp = { module = "javax.servlet.jsp:jsp-api", version.ref = "javax-jsp" }
javax-jstl = { module = "javax.servlet:jstl", version.ref = "javax-jstl" }
javax-persistence = { module = "javax.persistence:javax.persistence-api", version.ref = "javax-persistence" }
javax-servlet = { module = "javax.servlet:javax.servlet-api", version.ref = "javax-servlet" }
jline = { module = "jline:jline", version.ref = "jline" }
json-unit = { module = "net.javacrumbs.json-unit:json-unit", version.ref = "json-unit" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-engine", version.ref = "junit-platform" }
junit-platform-runner = { module = "org.junit.platform:junit-platform-runner", version.ref = "junit-platform" }
maven-model = { module = "org.apache.maven:maven-model", version.ref = "maven" }
maven-resolver-connectorBasic = { module = "org.apache.maven.resolver:maven-resolver-connector-basic", version.ref = "maven-resolver" }
maven-resolver-provider = { module = "org.apache.maven:maven-resolver-provider", version.ref = "maven" }
maven-resolver-impl = { module = "org.apache.maven.resolver:maven-resolver-impl", version.ref = "maven-resolver" }
maven-resolver-transportFile = { module = "org.apache.maven.resolver:maven-resolver-transport-file", version.ref = "maven-resolver" }
maven-resolver-transportHttp = { module = "org.apache.maven.resolver:maven-resolver-transport-http", version.ref = "maven-resolver" }
methvin-directoryWatcher = { module = "io.methvin:directory-watcher", version.ref = "methvin-directory-watcher" }
micronaut-aop = { module = "io.micronaut:micronaut-aop", version.ref = "micronaut-core" }
micronaut-bom = { module = "io.micronaut:micronaut-bom", version.ref = "micronaut-core" }
micronaut-cache-bom = { module = "io.micronaut.cache:micronaut-cache-bom", version.ref = "micronaut-cache" }
micronaut-context = { module = "io.micronaut:micronaut-context", version.ref = "micronaut-core" }
micronaut-core = { module = "io.micronaut:micronaut-core", version.ref = "micronaut-core" }
micronaut-inject = { module = "io.micronaut:micronaut-inject", version.ref = "micronaut-core" }
micronaut-inject-groovy = { module = "io.micronaut:micronaut-inject-groovy", version.ref = "micronaut-core" }
micronaut-runtime-groovy = { module = "io.micronaut.groovy:micronaut-runtime-groovy", version.ref = "micronaut-groovy" }
micronaut-spring = { module = "io.micronaut.spring:micronaut-spring", version.ref = "micronaut-spring" }
micronaut-spring-annotation = { module = "io.micronaut.spring:micronaut-spring-annotation", version.ref = "micronaut-spring" }
micronaut-spring-boot = { module = "io.micronaut.spring:micronaut-spring-boot", version.ref = "micronaut-spring" }
micronaut-spring-boot-annotation = { module = "io.micronaut.spring:micronaut-spring-boot-annotation", version.ref = "micronaut-spring" }
micronaut-spring-boot-starter = { module = "io.micronaut.spring:micronaut-spring-boot-starter", version.ref = "micronaut-spring" }
micronaut-spring-context = { module = "io.micronaut.spring:micronaut-spring-context", version.ref = "micronaut-spring" }
micronaut-spring-web = { module = "io.micronaut.spring:micronaut-spring-web", version.ref = "micronaut-spring" }
micronaut-spring-web-annotation = { module = "io.micronaut.spring:micronaut-spring-web-annotation", version.ref = "micronaut-spring" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
objenesis = { module = "org.objenesis:objenesis", version.ref = "objenesis" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-jcl = { module = "org.slf4j:jcl-over-slf4j", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
spock-spring = { module = "org.spockframework:spock-spring", version.ref = "spock" }
spring-aop = { module = "org.springframework:spring-aop", version.ref = "spring-framework" }
spring-aspects = { module = "org.springframework:spring-aspects", version.ref = "spring-framework" }
spring-beans = { module = "org.springframework:spring-beans", version.ref = "spring-framework" }
spring-boot = { module = "org.springframework.boot:spring-boot", version.ref = "spring-boot" }
spring-boot-actuator-autoconfigure = { module = "org.springframework.boot:spring-boot-actuator-autoconfigure", version.ref = "spring-boot" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring-boot" }
spring-boot-cli = { module = "org.springframework.boot:spring-boot-cli", version.ref = "spring-boot" }
spring-boot-configurationProcessor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "spring-boot" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-gradle-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-test", version.ref = "spring-boot" }
spring-context = { module = "org.springframework:spring-context", version.ref = "spring-framework" }
spring-contextSupport = { module = "org.springframework:spring-context-support", version.ref = "spring-framework" }
spring-core = { module = "org.springframework:spring-core", version.ref = "spring-framework" }
spring-dependency-management-plugin = { module = "io.spring.gradle:dependency-management-plugin", version.ref = "spring-dependency-management" }
spring-framework-bom = { module = "org.springframework:spring-framework-bom", version.ref = "spring-framework" }
spring-jdbc = { module = "org.springframework:spring-jdbc", version.ref = "spring-framework" }
spring-test = { module = "org.springframework:spring-test", version.ref = "spring-framework" }
spring-tx = { module = "org.springframework:spring-tx", version.ref = "spring-framework" }
spring-web = { module = "org.springframework:spring-web", version.ref = "spring-framework" }
spring-webmvc = { module = "org.springframework:spring-webmvc", version.ref = "spring-framework" }
spring-websocket = { module = "org.springframework:spring-websocket", version.ref = "spring-framework" }
standard-taglib = { module = "org.apache.taglibs:taglibs-standard-impl", version.ref = "standard-taglib" }
tomcat-jdbc = { module = "org.apache.tomcat:tomcat-jdbc", version.ref = "tomcat" }
tomcat-embed-core = { module = "org.apache.tomcat.embed:tomcat-embed-core", version.ref = "tomcat" }
xhtmlrenderer = { module = "org.xhtmlrenderer:core-renderer", version.ref = "xhtmlrenderer" }

[bundles]
bom = ["groovy-bom", "micronaut-cache-bom", "spring-framework-bom", "spring-boot-dependencies"]
grails-async = ["grails-async", "grails-async-gpars", "grails-async-rxjava", "grails-async-rxjava2", "grails-plugin-async"]
grails-devtools = ["methvin-directoryWatcher"]
grails-events = ["grails-events", "grails-events-compat", "grails-events-gpars", "grails-events-rxjava", "grails-events-rxjava2", "grails-events-spring", "grails-events-transform", "grails-plugin-events"]
grails-gorm = ["grails-datastore-core", "grails-datastore-async", "grails-datastore-gorm", "grails-datastore-gorm-async", "grails-datastore-gorm-hibernate5", "grails-datastore-gorm-support", "grails-datastore-gorm-test", "grails-datastore-gorm-validation"]
grails-gsp = ["grails-gsp", "grails-plugin-gsp", "grails-taglib", "grails-web-gsp", "grails-web-gsp-taglib", "grails-web-jsp", "grails-web-sitemesh", "grails-web-taglib"]
grails-scaffolding = ["grails-scaffolding-core"]
grails-views = ["grails-views-core", "grails-views-gradle", "grails-views-json", "grails-views-json-templates", "grails-views-json-testing-support", "grails-views-markup"]
groovy = ["groovy-bom"]
jakarta = ["jakarta-annotation-api"]
javax = ["javax-annotation", "javax-el", "javax-jaxb-api", "javax-inject", "javax-jsp", "javax-jstl", "javax-persistence", "javax-servlet"]
micronaut = ["micronaut-context", "micronaut-core", "micronaut-inject", "micronaut-inject-groovy"]
micronaut-cache = ["micronaut-cache-bom"]
micronaut-groovy = ["micronaut-runtime-groovy"]
micronaut-spring = ["micronaut-spring", "micronaut-spring-annotation", "micronaut-spring-boot", "micronaut-spring-boot-annotation", "micronaut-spring-boot-starter", "micronaut-spring-context", "micronaut-spring-web", "micronaut-spring-web-annotation"]
spock = ["spock-core", "spock-spring"]
spring-boot = ["spring-boot-dependencies"]
spring-framework = ["spring-framework-bom"]
snakeyaml = ["snakeyaml"]