dependencies {
    testImplementation project(":grace-boot")
    testImplementation project(":grace-bootstrap")
    testImplementation project(":grace-plugin-controllers")
    testImplementation project(":grace-plugin-databinding")
    testImplementation project(":grace-plugin-datasource")
    testImplementation project(":grace-plugin-domain-class")
    testImplementation project(":grace-plugin-i18n")
    testImplementation project(":grace-plugin-services")
    testImplementation project(":grace-plugin-url-mappings")
    testImplementation project(":grace-spring")
    testImplementation project(":grace-test-suite-base")
    testImplementation project(":grace-test-support")

    testImplementation libs.grace.async.core
    testImplementation libs.grace.datastore.gorm
    testImplementation libs.grace.datastore.gorm.validation

    api libs.tomcat.jdbc
    testRuntimeOnly libs.h2
    testRuntimeOnly libs.aspectj.rt
    testRuntimeOnly libs.aspectj.weaver
    testRuntimeOnly libs.spring.aspects
}

test {
    maxParallelForks = 2
    forkEvery = isCiBuild ? 25 : 100
    if (!isCiBuild) {
        maxHeapSize = '2048m'
    }

    excludes = [
        '**/GrailsDomainBinderTests.class',
        '**/ComponentValidationTests.class',
        '**/HibernateMappingUniqueConstraintTests.class'
    ]
}

task testGrailsDomainBinder(type: Test) {
    includes = [
        '**/GrailsDomainBinderTests.class'
    ]
}

task testIsolatedPersistentOne(type: Test) {
    includes = [
        '**/ComponentValidationTests.class',
        '**/HibernateMappingUniqueConstraintTests.class'
    ]
}

test {
    dependsOn = [testGrailsDomainBinder, testIsolatedPersistentOne]
}
