dependencies {
    api project(":grace-api")
    api project(":grace-bootstrap")
    api project(":grace-core")
    api project(":grace-plugin-api")
    api project(":grace-plugin-mimetypes")
    api project(":grace-plugin-validation")
    api project(":grace-util")
    api project(":grace-web")

    compileOnly libs.jakarta.servlet
    api(libs.spring.boot.autoconfigure)
    annotationProcessor libs.spring.boot.autoconfigureProcessor
    annotationProcessor libs.spring.boot.configurationProcessor

    testImplementation project(":grace-test")
    testImplementation libs.jakarta.servlet
}
