contact_links:
  - name: Grace Discussions
    url: https://github.com/graceframework/grace-framework/discussions
    about: Ask questions about Grace framework on Github
  - name: Stack Overflow
    url: https://stackoverflow.com/tags/graceframework
    about: Ask questions on Stack Overflow