dependencies {
    api project(":grace-util")

    compileOnly(libs.grace.datastore.core) {
        transitive = false
    }

    api(libs.slf4j.api)
    api(libs.spring.beans)
    api libs.spring.context, {
        exclude group: 'io.micrometer', module: 'micrometer-observation'
    }
    api(libs.spring.core)
}
