buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven {
            url = 'https://repo.gradle.org/gradle/libs-releases'
        }
    }
    dependencies {
        classpath "org.graceframework:grace-gradle-plugin:$graceVersion"
        classpath "io.github.gradle-nexus:publish-plugin:2.0.0"
        classpath "io.spring.gradle:dependency-management-plugin:$springDependencyManagementPluginVersion"
    }
}

group = "org.graceframework"

apply plugin: "io.spring.dependency-management"

ext {
    userOrg = 'graceframework'
    repo = 'grace-views'
    isGrailsPlugin = false
    projectDesc = "Grace Views Core"
}

repositories {
    mavenCentral()
}

dependencies {
    api "org.apache.groovy:groovy:$groovyVersion"
    api "org.graceframework:grace-core:$graceVersion", {
        exclude group: 'org.graceframework', module: 'grace-datastore-core'
    }
    api "org.graceframework:grace-encoder:$graceVersion"
    api "org.graceframework:grace-web-common:$graceVersion"
    api "org.graceframework:grace-web-url-mappings:$graceVersion", {
        exclude group: 'org.graceframework', module: 'grace-datastore-gorm-validation'
    }
    api "org.graceframework:grace-plugin-rest:$graceVersion"
    api "org.graceframework:grace-datastore-gorm-support:$gormVersion"
    api "com.github.ben-manes.caffeine:caffeine:$caffeineVersion"
    compileOnly "jakarta.servlet:jakarta.servlet-api:$servletApiVersion"
}
