dependencies {
    api project(":grace-core")
    api project(":grace-views-core")
    api libs.jakarta.annotation.api
    compileOnly libs.jakarta.servlet

    api libs.spring.boot.autoconfigure
    annotationProcessor libs.spring.boot.autoconfigureProcessor
    annotationProcessor libs.spring.boot.configurationProcessor

    testImplementation project(":grace-test-support")
}
