dependencies {
    api project(":grace-api")
    compileOnly project(":grace-plugin-api")
    api project(":grace-util")
    api project(":grace-web")
    api project(":grace-web-mvc")

    api(libs.grace.datastore.gorm.validation)

    compileOnlyApi libs.jakarta.servlet
    implementation libs.caffeine

    testImplementation libs.jakarta.servlet
    testImplementation project(":grace-test-suite-base")
    testImplementation project(":grace-plugin-url-mappings")
}

tasks.withType(Test) {
    testLogging {
        exceptionFormat = 'full'
//        showStandardStreams = true
    }
    afterSuite {
        System.out.print(".")
        System.out.flush()
    }
}
