group = "org.graceframework"

dependencies {
    api "org.graceframework:grace-core:$graceVersion", {
        exclude group: 'org.graceframework', module: 'grace-datastore-core'
    }
    compileOnly "jakarta.servlet:jakarta.servlet-api:$servletApiVersion"

    api "org.graceframework:grace-test-support:$graceVersion"
    api project(":views-json")
}
