group = "org.graceframework"

dependencies {
    api project(":views-json")
    api "org.graceframework:grace-core", {
        exclude group: 'org.graceframework', module: 'grace-datastore-core'
    }
    compileOnly "jakarta.servlet:jakarta.servlet-api"

    api "org.graceframework:grace-test-support"
}
