dependencies {
    api libs.groovy.core
    api project(":grace-core")
    api project(":grace-encoder")
    api project(":grace-plugin-domain-class")
    api project(":grace-plugin-rest")
    api project(":grace-web")
    api project(":grace-web-url-mappings")
    api libs.grace.datastore.gorm.support
    api libs.caffeine
    compileOnly libs.jakarta.servlet
}
