apply plugin: 'maven-publish'

def PLUGINS = [
    'async',
    'cache',
    'codecs',
    'converters',
    'core',
    'databinding',
    'domain-class',
    'events',
    'gsp',
    'i18n',
    'interceptors',
    'mimetypes',
    'rest',
    'services',
    'url-mappings',
    'validation'
]

publishing {
    publications {
        maven(MavenPublication) {
            pom.withXml {
                def xml = asNode()

                xml.children().last() + {
                    delegate.dependencies {
                        delegate.dependency {
                            delegate.groupId "org.graceframework"
                            delegate.artifactId "grace-bootstrap"
                            delegate.version(project.version)
                            delegate.scope "compile"
                        }
                        delegate.dependency {
                            delegate.groupId "org.graceframework"
                            delegate.artifactId "grace-boot"
                            delegate.version(project.version)
                            delegate.scope "provided"
                        }
                        delegate.dependency {
                            delegate.groupId "org.graceframework"
                            delegate.artifactId "grace-core"
                            delegate.version(project.version)
                            delegate.scope "compile"
                        }
                        for(plug in PLUGINS) {
                            delegate.dependency {
                                delegate.groupId "org.graceframework"
                                delegate.artifactId "grace-plugin-${plug}"
                                delegate.version(project.version)
                                delegate.scope "compile"
                            }
                        }
                        delegate.dependency {
                            delegate.groupId "org.graceframework"
                            delegate.artifactId "grace-test"
                            delegate.version(project.version)
                            delegate.scope "test"
                        }
                        delegate.dependency {
                            delegate.groupId "org.graceframework"
                            delegate.artifactId "grace-test-support"
                            delegate.version(project.version)
                            delegate.scope "test"
                        }
                        delegate.dependency {
                            delegate.groupId "com.h2database"
                            delegate.artifactId "h2"
                            delegate.version libs.versions.h2.get()
                            delegate.scope "test"
                        }
                    }
                }
            }
        }
    }
}
