api=../api
guide=../../guide
tags=../ref/Tags
github=https://github.com/graceframework/grace-framework
sourcedir=.
sourceRepo=https://github.com/graceframework/grace-framework/edit/2023.3.x/docs/src/docs
safe=UNSAFE
title=Grace Framework
subtitle=A powerful and open-source One-Person web framework used to build enterprise-grade Spring Boot applications
authors=Michael Yan
copyright=Copyright &copy; 2022-2025 Michael Yan and the original authors. The content is licensed under a Creative Commons Attribution 4.0 International (CC BY SA 4.0) license.
