dependencies {
    compileOnly libs.ant
    compileOnlyApi libs.jakarta.servlet
    api project(":grace-gsp")
    compileOnly project(":grace-plugin-domain-class")
    api project(":grace-web-common")
    api project(":grace-web-taglib")
    api project(":grace-web-sitemesh")

    testImplementation libs.jakarta.servlet
    testImplementation libs.spring.test
    testImplementation project(":grace-test")
    testRuntimeOnly project(":grace-spring")
}
