import org.grails.gradle.plugin.web.gsp.GroovyPageCompileTask

group = "org.graceframework.plugins"

apply plugin: "org.graceframework.grace-plugin"

dependencies {
    api "jakarta.annotation:jakarta.annotation-api:$jakartaAnnotationVersion"
    api "org.graceframework:grace-core:$graceVersion", {
        exclude group: 'org.graceframework', module: 'grace-datastore-core'
    }
    compileOnly "jakarta.servlet:jakarta.servlet-api:$servletApiVersion"
    compileOnly "org.graceframework:grace-boot:$graceVersion"
    api project(":views-core")

    api "org.springframework.boot:spring-boot-autoconfigure"
    annotationProcessor "org.springframework.boot:spring-boot-autoconfigure-processor"
    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"
    api "org.graceframework:grace-datastore-gorm:$gormVersion"
    testImplementation "org.graceframework:grace-test-support:$graceVersion"
    testImplementation project(":views-json-testing-support")
    testImplementation "net.bytebuddy:byte-buddy:$bytebuddyVersion"
    testRuntimeOnly "org.javassist:javassist:$javassistVersion"
}

tasks.withType(GroovyPageCompileTask) {
    classpath += configurations.compileClasspath
}

jar {
    exclude "*.gson"
    enabled = true
    archiveClassifier.set('plugin')
    includeEmptyDirs = false
}
