dependencies {
    api project(":grace-api")
    compileOnly project(":grace-plugin-api")
    api project(":grace-web")
    api project(":grace-web-databinding")

    compileOnly libs.jakarta.servlet
    api libs.spring.boot.autoconfigure
    annotationProcessor libs.spring.boot.autoconfigureProcessor
    annotationProcessor libs.spring.boot.configurationProcessor

    testImplementation project(":grace-test-support")
    testImplementation libs.grace.datastore.gorm.support
}
