dependencies {
    api project(":grace-web-common")
    api project(":grace-web-gsp")

    compileOnlyApi libs.jakarta.servlet
    // Required for JSP support
    implementation libs.jakarta.servlet.jsp
    implementation libs.jakarta.servlet.jsp.jstl
    implementation libs.jakarta.el
    implementation libs.glassfish.web.jsp.jstl
}
