dependencies {
    api project(":grace-web-common")
    api project(":grace-web-gsp")

    compileOnlyApi libs.jakarta.servlet
    // Required for JSP support
    compileOnlyApi libs.jakarta.el
    compileOnlyApi libs.jakarta.servlet.jsp, {
        exclude group: 'jakarta.servlet', module: 'jakarta.servlet-api'
    }
    compileOnlyApi libs.jakarta.servlet.jsp.jstl, {
        exclude group: 'jakarta.el', module: 'jakarta.el-api'
        exclude group: 'jakarta.servlet', module: 'jakarta.servlet-api'
    }
    compileOnly libs.glassfish.web.jsp.jstl
}
