dependencies {
    api project(":grace-core")
    compileOnly project(":grace-plugin-api")
    api project(":grace-plugin-validation")
    api project(":grace-views-core")

    api libs.groovy.json
    api libs.spring.boot.autoconfigure
    annotationProcessor libs.spring.boot.autoconfigureProcessor
    annotationProcessor libs.spring.boot.configurationProcessor

    testImplementation project(":grace-test-support")
}
