dependencies {
    api project(":grace-databinding")
    api project(":grace-util")
    api project(":grace-web-common")

    api libs.grails.datastore.core, {
        transitive = false
    }

    compileOnly libs.jakarta.servlet

    testImplementation libs.jakarta.servlet
    testImplementation libs.spring.test
}
