dependencies {
    compileOnly project(":grace-core")
    compileOnly project(":grace-plugin-api")
    api libs.geb.core
    api libs.geb.spock
    implementation libs.selenium.api
    implementation libs.selenium.support
    implementation libs.selenium.chromeDriver
    implementation libs.selenium.firefoxDriver
}

tasks.register("syncScripts", Sync) {
    from("src/main/scripts")
    into("build/resources/main/META-INF/commands")
}

tasks.register("syncTemplates", Sync) {
    from("src/main/templates")
    into("build/resources/main/META-INF/templates")
}

processResources {
    dependsOn = ["syncScripts", "syncTemplates"]
}
