dependencies {
    api libs.geb.core
    api libs.geb.spock
    compileOnly project(":grace-plugin-api")
    compileOnly project(":grace-core")
}

tasks.register("syncScripts", Sync) {
    from("src/main/scripts")
    into("build/resources/main/META-INF/commands")
}

tasks.register("syncTemplates", Sync) {
    from("src/main/templates")
    into("build/resources/main/META-INF/templates")
}

processResources {
    dependsOn = ["syncScripts", "syncTemplates"]
}
