buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath "org.graceframework:grace-gradle-plugin:$graceVersion"
        classpath "org.graceframework.plugins:views-gradle:$functionalTestViewsGradleVersion"
        classpath "org.graceframework.plugins:asset-pipeline-gradle:$assetPipelineVersion"
        classpath "org.gradle:test-retry-gradle-plugin:1.6.0"
    }
}

version "0.1"
group "functional.tests"

apply plugin: "eclipse"
apply plugin: "idea"
apply plugin: "war"
apply plugin: "org.graceframework.asset-pipeline"
apply plugin: "org.graceframework.grace-web"
apply plugin: "org.graceframework.grace-gsp"
apply plugin: "org.graceframework.plugins.views-json"
apply plugin: "org.graceframework.plugins.views-markup"
apply plugin: "org.gradle.test-retry"

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.graceframework:grace-boot"
    implementation "org.graceframework:grace-core"
    implementation "org.graceframework:grace-logging"
    implementation "org.graceframework.plugins:hibernate"
    implementation "org.graceframework.plugins:mongodb"
    implementation "org.graceframework.plugins:cache"
    implementation "org.graceframework.plugins:scaffolding"

    implementation project(":views-json")
    implementation project(":views-markup")
    implementation project(":examples-functional-tests-plugin")

    runtimeOnly "org.graceframework.plugins:asset-pipeline-plugin:$assetPipelineVersion"
    runtimeOnly project(":views-json-templates")

    testImplementation project(":views-json-testing-support")
}

integrationTest {
    testLogging {
        showStandardStreams = true
        exceptionFormat = 'full'
    }
}

tasks.withType(Test) {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
        exceptionFormat = 'full'
    }
}
