dependencies {
    api project(":grace-core")
    api project(":grace-plugin-api")
    api project(":grace-plugin-validation")
    api project(":grace-spring")

    api libs.jakarta.persistence.api
    api(libs.grace.datastore.core)
    api(libs.grace.datastore.gorm)
    api(libs.grace.datastore.gorm.support)
    api(libs.grace.datastore.gorm.validation)
    api libs.spring.boot.autoconfigure
    annotationProcessor libs.spring.boot.autoconfigureProcessor
    annotationProcessor libs.spring.boot.configurationProcessor

    testImplementation libs.assertj.core
    testImplementation libs.spring.boot.test
}
