dependencies {
    api libs.groovy.xml
    compileOnly libs.spring.aop
    api libs.spring.core
    api libs.spring.beans
    api libs.spring.context
    compileOnly libs.spring.tx
    compileOnly libs.spring.web

    testRuntimeOnly libs.spring.aspects
    testRuntimeOnly libs.aspectj.rt
    testRuntimeOnly libs.aspectj.weaver
}
