dependencies {
    api project(":grace-api")
    api project(":grace-bootstrap")
    api project(":grace-core")
    compileOnly project(':grace-plugin-api')
    api project(":grace-plugin-controllers")
    api project(":grace-plugin-converters")
    api project(":grace-util")
    api project(":grace-web-rest")
    api project(":grace-web-url-mappings")

    compileOnly libs.jakarta.servlet
    api libs.jakarta.xml.bind.api
    api libs.spring.boot.autoconfigure
    annotationProcessor libs.spring.boot.autoconfigureProcessor
    annotationProcessor libs.spring.boot.configurationProcessor
    compileOnly(libs.grace.datastore.core) {
        transitive = false
    }
    compileOnly(libs.grace.datastore.gorm) {
        transitive = false
    }
    compileOnly libs.grace.datastore.gorm.support
    compileOnly project(":grace-web-gsp")
    implementation libs.caffeine

    testImplementation libs.jakarta.servlet
    testImplementation libs.grace.datastore.gorm.support
    testImplementation project(":grace-plugin-url-mappings")
    testImplementation project(":grace-test-suite-base")
}
