dependencies {
    compileOnly "org.graceframework:grace-core"
    compileOnly "org.graceframework:grace-bootstrap"
    compileOnly "org.graceframework:grace-boot"
    compileOnly "org.spockframework:spock-core:$spockVersion", {
        exclude group: "junit", module: "junit-dep"
        exclude group: 'org.codehaus.groovy', module: 'groovy-all'
        exclude group: 'org.hamcrest', module: 'hamcrest-core'
    }

    api "org.graceframework:grace-datastore-web:$datastoreVersion"
    api "org.graceframework:grace-datastore-gorm-support:$datastoreVersion", {
        exclude group:'org.springframework', module:'spring-context'
        exclude group:'org.springframework', module:'spring-core'
        exclude group:'org.springframework', module:'spring-beans'
        exclude group:'org.springframework', module:'spring-tx'
        exclude group:'org.graceframework', module:'grace-bootstrap'
        // exclude group:'org.codehaus.groovy', module:'groovy-all'
        exclude group:'org.graceframework', module:'grace-core'
        exclude group:'javax.transaction', module:'jta'
    }
    api project(":grace-datastore-gorm-mongodb-ext"), {
        exclude group:'org.graceframework', module:'grace-datastore-gorm-mongodb'
    }    
    api project(":grace-datastore-gorm-mongodb"), {
        exclude group:'org.springframework', module:'spring-context'
        exclude group:'org.springframework', module:'spring-core'
        exclude group:'org.springframework', module:'spring-beans'
        exclude group:'org.springframework', module:'spring-tx'
        exclude group:'org.graceframework', module:'grace-bootstrap'
        exclude group:'org.codehaus.groovy', module:'groovy-all'
        exclude group:'org.graceframework', module:'grace-core'
        exclude group:'javax.transaction', module:'jta'
    }
}
