dependencies {
    api libs.groovy.sql
    api libs.liquibase.core
    api libs.spring.jdbc
    api libs.spring.tx
    implementation project(":grace-bootstrap")
    implementation project(":grace-cli")
    implementation project(":grace-core")
    compileOnly project(":grace-plugin-api")
    compileOnly project(":grace-shell")
    implementation libs.grace.datastore.gorm

    api libs.spring.boot.autoconfigure
    annotationProcessor libs.spring.boot.autoconfigureProcessor
    annotationProcessor libs.spring.boot.configurationProcessor

    testImplementation project(":grace-shell")
    testImplementation project(":grace-test-support")
    testImplementation libs.h2
}

tasks.register("syncScripts", Sync) {
    from("src/main/scripts")
    into("build/resources/main/META-INF/commands")
}

processResources {
    dependsOn = ["syncScripts"]
}
