name: Retry Release
on:
  workflow_dispatch:
    inputs:
      release:
        description: The Grace Release (e.g. 5.0.3)
        required: true
      target_branch:
        description: The Target Branch (e.g. 5.0.x)
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8']
    env:
      GIT_USER_NAME: rainboyan
      GIT_USER_EMAIL: rain@rainboyan.com
      GRADLE_OPTS: -Xmx1500m -Dfile.encoding=UTF-8
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "v${{ github.event.inputs.release }}"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Extract Target Branch
        id: extract_branch
        run: |
          echo $TARGET_BRANCH
          echo ::set-output name=value::${TARGET_BRANCH}
        env:
          TARGET_BRANCH: ${{ github.event.inputs.target_branch }}
      - name: Set the current release version
        id: release_version
        run: echo ::set-output name=release_version::${VERSION}
        env:
          VERSION: ${{ github.event.inputs.release }}
      - name: Run Assemble
        id: assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
      - name: Export Gradle Properties
        uses: micronaut-projects/github-actions/export-gradle-properties@master
      - name: Upload artifacts to the Github release
        id: upload_artifact
        if: steps.assemble.outcome == 'success'
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          created_tag: v${{ github.event.inputs.release }}
          args: build/distributions/grace-${{ steps.release_version.outputs.release_version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}