name: SDKMAN Release

on:
  release:
    types: [published]

permissions: {}
jobs:
  sdkman_release:
    if: ${{ github.repository == 'graceframework/grace-framework' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref_name }}
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      - name: SDKMan release
        run: ./gradlew sdkManRelease
        env:
          SDKMAN_KEY: ${{ secrets.SDKMAN_KEY }}
          SDKMAN_TOKEN: ${{ secrets.SDKMAN_TOKEN }}
