name: SDKMAN Release

on:
  release:
    types: [published]

permissions: {}
jobs:
  sdkman_release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: ['11']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref_name }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: SDKMan release
        uses: gradle/actions/setup-gradle@v3
        env:
          SDKMAN_KEY: ${{ secrets.SDKMAN_KEY }}
          SDKMAN_TOKEN: ${{ secrets.SDKMAN_TOKEN }}
        run: ./gradlew sdkManRelease
