name: SDKMAN Release

on:
  release:
    types: [published]

permissions: {}
jobs:
  sdkman_release:
    if: ${{ github.repository == 'graceframework/grace-framework' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref_name }}
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
      - name: SDKMan release
        run: ./gradlew sdkManRelease
        env:
          SDKMAN_KEY: ${{ secrets.SDKMAN_KEY }}
          SDKMAN_TOKEN: ${{ secrets.SDKMAN_TOKEN }}
